// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: identity/service.proto

package identity

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_identity_service_proto protoreflect.FileDescriptor

const file_identity_service_proto_rawDesc = "" +
	"\n" +
	"\x16identity/service.proto\x12\bidentity\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17identity/messages.proto2\xf4\x04\n" +
	"\x0fIdentityService\x12B\n" +
	"\vHealthCheck\x12\x17.identity.HealthRequest\x1a\x18.identity.HealthResponse\"\x00\x12z\n" +
	"\aAddUser\x12\x18.identity.AddUserRequest\x1a\x19.identity.AddUserResponse\":\x92A\x1b\n" +
	"\x05Users\x12\bAdd user\x1a\bAdd user\x82\xd3\xe4\x93\x02\x16:\x01*b\x02id\"\r/api/v1/users\x12\x84\x01\n" +
	"\aGetUser\x12\x18.identity.GetUserRequest\x1a\x19.identity.GetUserResponse\"D\x92A!\n" +
	"\x05Users\x12\bGet user\x1a\x0eGet user by ID\x82\xd3\xe4\x93\x02\x1ab\x04user\x12\x12/api/v1/users/{id}\x12\x8d\x01\n" +
	"\n" +
	"DeleteUser\x12\x1b.identity.DeleteUserRequest\x1a\x1c.identity.DeleteUserResponse\"D\x92A'\n" +
	"\x05Users\x12\vDelete user\x1a\x11Delete user by ID\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/users/{id}\x12\x89\x01\n" +
	"\tListUsers\x12\x1a.identity.ListUsersRequest\x1a\x1b.identity.ListUsersResponse\"A\x92A#\n" +
	"\x05Users\x12\n" +
	"List users\x1a\x0eList all users\x82\xd3\xe4\x93\x02\x15b\x04user\x12\r/api/v1/users0\x01B\xaf\x01\x92Az\x12&\n" +
	"\x1cinvenlore.io OpenAPI Swagger2\x06latest*\x01\x02rM\n" +
	"'gRPC-gateway invenlore proto repository\x12\"https://github.com/invenlore/protoZ0github.com/invenlore/proto/pkg/identity;identityb\x06proto3"

var file_identity_service_proto_goTypes = []any{
	(*HealthRequest)(nil),      // 0: identity.HealthRequest
	(*AddUserRequest)(nil),     // 1: identity.AddUserRequest
	(*GetUserRequest)(nil),     // 2: identity.GetUserRequest
	(*DeleteUserRequest)(nil),  // 3: identity.DeleteUserRequest
	(*ListUsersRequest)(nil),   // 4: identity.ListUsersRequest
	(*HealthResponse)(nil),     // 5: identity.HealthResponse
	(*AddUserResponse)(nil),    // 6: identity.AddUserResponse
	(*GetUserResponse)(nil),    // 7: identity.GetUserResponse
	(*DeleteUserResponse)(nil), // 8: identity.DeleteUserResponse
	(*ListUsersResponse)(nil),  // 9: identity.ListUsersResponse
}
var file_identity_service_proto_depIdxs = []int32{
	0, // 0: identity.IdentityService.HealthCheck:input_type -> identity.HealthRequest
	1, // 1: identity.IdentityService.AddUser:input_type -> identity.AddUserRequest
	2, // 2: identity.IdentityService.GetUser:input_type -> identity.GetUserRequest
	3, // 3: identity.IdentityService.DeleteUser:input_type -> identity.DeleteUserRequest
	4, // 4: identity.IdentityService.ListUsers:input_type -> identity.ListUsersRequest
	5, // 5: identity.IdentityService.HealthCheck:output_type -> identity.HealthResponse
	6, // 6: identity.IdentityService.AddUser:output_type -> identity.AddUserResponse
	7, // 7: identity.IdentityService.GetUser:output_type -> identity.GetUserResponse
	8, // 8: identity.IdentityService.DeleteUser:output_type -> identity.DeleteUserResponse
	9, // 9: identity.IdentityService.ListUsers:output_type -> identity.ListUsersResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_identity_service_proto_init() }
func file_identity_service_proto_init() {
	if File_identity_service_proto != nil {
		return
	}
	file_identity_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_service_proto_rawDesc), len(file_identity_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_service_proto_goTypes,
		DependencyIndexes: file_identity_service_proto_depIdxs,
	}.Build()
	File_identity_service_proto = out.File
	file_identity_service_proto_goTypes = nil
	file_identity_service_proto_depIdxs = nil
}
