// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: common/v1/context.proto

// Shared request context passed via gRPC metadata.
// Canonical metadata keys:
// - x-request-id
// - x-user-id
// - x-roles (comma-separated)
// - x-tenant-id
// - x-idempotency-key

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RequestContext describes values propagated through gRPC metadata.
// Note: it is not embedded into request/response messages.
type RequestContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles          []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	TenantId       string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	mi := &file_common_v1_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_common_v1_context_proto_rawDescGZIP(), []int{0}
}

func (x *RequestContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestContext) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *RequestContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RequestContext) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

var File_common_v1_context_proto protoreflect.FileDescriptor

const file_common_v1_context_proto_rawDesc = "" +
	"\n" +
	"\x17common/v1/context.proto\x12\tcommon.v1\"\xa4\x01\n" +
	"\x0eRequestContext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKeyB3Z1github.com/invenlore/proto/pkg/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_context_proto_rawDescOnce sync.Once
	file_common_v1_context_proto_rawDescData []byte
)

func file_common_v1_context_proto_rawDescGZIP() []byte {
	file_common_v1_context_proto_rawDescOnce.Do(func() {
		file_common_v1_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_context_proto_rawDesc), len(file_common_v1_context_proto_rawDesc)))
	})
	return file_common_v1_context_proto_rawDescData
}

var file_common_v1_context_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_context_proto_goTypes = []any{
	(*RequestContext)(nil), // 0: common.v1.RequestContext
}
var file_common_v1_context_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_context_proto_init() }
func file_common_v1_context_proto_init() {
	if File_common_v1_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_context_proto_rawDesc), len(file_common_v1_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_context_proto_goTypes,
		DependencyIndexes: file_common_v1_context_proto_depIdxs,
		MessageInfos:      file_common_v1_context_proto_msgTypes,
	}.Build()
	File_common_v1_context_proto = out.File
	file_common_v1_context_proto_goTypes = nil
	file_common_v1_context_proto_depIdxs = nil
}
