// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: common/v1/errors.proto

// Shared error model conventions for invenlore services.

package commonv1

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorEnvelope wraps google.rpc.Status to standardize error payloads.
type ErrorEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gRPC status payload with optional details.
	Status        *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEnvelope) Reset() {
	*x = ErrorEnvelope{}
	mi := &file_common_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEnvelope) ProtoMessage() {}

func (x *ErrorEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEnvelope.ProtoReflect.Descriptor instead.
func (*ErrorEnvelope) Descriptor() ([]byte, []int) {
	return file_common_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorEnvelope) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_common_v1_errors_proto protoreflect.FileDescriptor

const file_common_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x16common/v1/errors.proto\x12\tcommon.v1\x1a\x17google/rpc/status.proto\";\n" +
	"\rErrorEnvelope\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06statusB3Z1github.com/invenlore/proto/pkg/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_errors_proto_rawDescOnce sync.Once
	file_common_v1_errors_proto_rawDescData []byte
)

func file_common_v1_errors_proto_rawDescGZIP() []byte {
	file_common_v1_errors_proto_rawDescOnce.Do(func() {
		file_common_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_errors_proto_rawDesc), len(file_common_v1_errors_proto_rawDesc)))
	})
	return file_common_v1_errors_proto_rawDescData
}

var file_common_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_errors_proto_goTypes = []any{
	(*ErrorEnvelope)(nil), // 0: common.v1.ErrorEnvelope
	(*status.Status)(nil), // 1: google.rpc.Status
}
var file_common_v1_errors_proto_depIdxs = []int32{
	1, // 0: common.v1.ErrorEnvelope.status:type_name -> google.rpc.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_v1_errors_proto_init() }
func file_common_v1_errors_proto_init() {
	if File_common_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_errors_proto_rawDesc), len(file_common_v1_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_errors_proto_goTypes,
		DependencyIndexes: file_common_v1_errors_proto_depIdxs,
		MessageInfos:      file_common_v1_errors_proto_msgTypes,
	}.Build()
	File_common_v1_errors_proto = out.File
	file_common_v1_errors_proto_goTypes = nil
	file_common_v1_errors_proto_depIdxs = nil
}
