// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: common/v1/openapi.proto

// Shared OpenAPI configuration for invenlore public API.

package commonv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_common_v1_openapi_proto protoreflect.FileDescriptor

const file_common_v1_openapi_proto_rawDesc = "" +
	"\n" +
	"\x17common/v1/openapi.proto\x12\tcommon.v1\x1a.protoc-gen-openapiv2/options/annotations.protoB\xb5\x02\x92A\xfe\x01\x12&\n" +
	"\x1cinvenlore.io OpenAPI Swagger2\x06latest*\x01\x02Zp\n" +
	"n\n" +
	"\n" +
	"BearerAuth\x12`\b\x02\x12KJWT Authorization header using the Bearer scheme. Example: 'Bearer {token}'\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00rM\n" +
	"'gRPC-gateway invenlore proto repository\x12\"https://github.com/invenlore/protoZ1github.com/invenlore/proto/pkg/common/v1;commonv1b\x06proto3"

var file_common_v1_openapi_proto_goTypes = []any{}
var file_common_v1_openapi_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_openapi_proto_init() }
func file_common_v1_openapi_proto_init() {
	if File_common_v1_openapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_openapi_proto_rawDesc), len(file_common_v1_openapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_openapi_proto_goTypes,
		DependencyIndexes: file_common_v1_openapi_proto_depIdxs,
	}.Build()
	File_common_v1_openapi_proto = out.File
	file_common_v1_openapi_proto_goTypes = nil
	file_common_v1_openapi_proto_depIdxs = nil
}
