// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: common/v1/utils.proto

// Shared service utils.

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Health check request.
type ServiceHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHealthRequest) Reset() {
	*x = ServiceHealthRequest{}
	mi := &file_common_v1_utils_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHealthRequest) ProtoMessage() {}

func (x *ServiceHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_utils_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHealthRequest.ProtoReflect.Descriptor instead.
func (*ServiceHealthRequest) Descriptor() ([]byte, []int) {
	return file_common_v1_utils_proto_rawDescGZIP(), []int{0}
}

// Health check response.
type ServiceHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHealthResponse) Reset() {
	*x = ServiceHealthResponse{}
	mi := &file_common_v1_utils_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHealthResponse) ProtoMessage() {}

func (x *ServiceHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_utils_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHealthResponse.ProtoReflect.Descriptor instead.
func (*ServiceHealthResponse) Descriptor() ([]byte, []int) {
	return file_common_v1_utils_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_common_v1_utils_proto protoreflect.FileDescriptor

const file_common_v1_utils_proto_rawDesc = "" +
	"\n" +
	"\x15common/v1/utils.proto\x12\tcommon.v1\"\x16\n" +
	"\x14ServiceHealthRequest\"/\n" +
	"\x15ServiceHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06statusB3Z1github.com/invenlore/proto/pkg/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_utils_proto_rawDescOnce sync.Once
	file_common_v1_utils_proto_rawDescData []byte
)

func file_common_v1_utils_proto_rawDescGZIP() []byte {
	file_common_v1_utils_proto_rawDescOnce.Do(func() {
		file_common_v1_utils_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_utils_proto_rawDesc), len(file_common_v1_utils_proto_rawDesc)))
	})
	return file_common_v1_utils_proto_rawDescData
}

var file_common_v1_utils_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_v1_utils_proto_goTypes = []any{
	(*ServiceHealthRequest)(nil),  // 0: common.v1.ServiceHealthRequest
	(*ServiceHealthResponse)(nil), // 1: common.v1.ServiceHealthResponse
}
var file_common_v1_utils_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_utils_proto_init() }
func file_common_v1_utils_proto_init() {
	if File_common_v1_utils_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_utils_proto_rawDesc), len(file_common_v1_utils_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_utils_proto_goTypes,
		DependencyIndexes: file_common_v1_utils_proto_depIdxs,
		MessageInfos:      file_common_v1_utils_proto_msgTypes,
	}.Build()
	File_common_v1_utils_proto = out.File
	file_common_v1_utils_proto_goTypes = nil
	file_common_v1_utils_proto_depIdxs = nil
}
