// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: wiki/v1/events.proto

// Wiki outbox event payloads.

package wikiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PageRevisionCreated is emitted when a new revision is created.
type PageRevisionCreated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page id.
	PageId string `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	// Revision id.
	RevisionId string `protobuf:"bytes,2,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	// Space id.
	SpaceId string `protobuf:"bytes,3,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// Page slug.
	Slug string `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	// Page title.
	Title string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	// Author id.
	AuthorId string `protobuf:"bytes,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	// Event creation timestamp.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRevisionCreated) Reset() {
	*x = PageRevisionCreated{}
	mi := &file_wiki_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRevisionCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRevisionCreated) ProtoMessage() {}

func (x *PageRevisionCreated) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRevisionCreated.ProtoReflect.Descriptor instead.
func (*PageRevisionCreated) Descriptor() ([]byte, []int) {
	return file_wiki_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *PageRevisionCreated) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *PageRevisionCreated) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *PageRevisionCreated) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *PageRevisionCreated) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *PageRevisionCreated) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PageRevisionCreated) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *PageRevisionCreated) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// PageAclChanged is emitted when page ACL snapshot changes.
type PageAclChanged struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page id.
	PageId string `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	// Updated permission snapshot.
	Perms *PermissionSnapshot `protobuf:"bytes,2,opt,name=perms,proto3" json:"perms,omitempty"`
	// Event creation timestamp.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageAclChanged) Reset() {
	*x = PageAclChanged{}
	mi := &file_wiki_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageAclChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageAclChanged) ProtoMessage() {}

func (x *PageAclChanged) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageAclChanged.ProtoReflect.Descriptor instead.
func (*PageAclChanged) Descriptor() ([]byte, []int) {
	return file_wiki_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *PageAclChanged) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *PageAclChanged) GetPerms() *PermissionSnapshot {
	if x != nil {
		return x.Perms
	}
	return nil
}

func (x *PageAclChanged) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_wiki_v1_events_proto protoreflect.FileDescriptor

const file_wiki_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x14wiki/v1/events.proto\x12\awiki.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16wiki/v1/messages.proto\"\xec\x01\n" +
	"\x13PageRevisionCreated\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x1f\n" +
	"\vrevision_id\x18\x02 \x01(\tR\n" +
	"revisionId\x12\x19\n" +
	"\bspace_id\x18\x03 \x01(\tR\aspaceId\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x1b\n" +
	"\tauthor_id\x18\x06 \x01(\tR\bauthorId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x97\x01\n" +
	"\x0ePageAclChanged\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x121\n" +
	"\x05perms\x18\x02 \x01(\v2\x1b.wiki.v1.PermissionSnapshotR\x05perms\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB/Z-github.com/invenlore/proto/pkg/wiki/v1;wikiv1b\x06proto3"

var (
	file_wiki_v1_events_proto_rawDescOnce sync.Once
	file_wiki_v1_events_proto_rawDescData []byte
)

func file_wiki_v1_events_proto_rawDescGZIP() []byte {
	file_wiki_v1_events_proto_rawDescOnce.Do(func() {
		file_wiki_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wiki_v1_events_proto_rawDesc), len(file_wiki_v1_events_proto_rawDesc)))
	})
	return file_wiki_v1_events_proto_rawDescData
}

var file_wiki_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wiki_v1_events_proto_goTypes = []any{
	(*PageRevisionCreated)(nil),   // 0: wiki.v1.PageRevisionCreated
	(*PageAclChanged)(nil),        // 1: wiki.v1.PageAclChanged
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*PermissionSnapshot)(nil),    // 3: wiki.v1.PermissionSnapshot
}
var file_wiki_v1_events_proto_depIdxs = []int32{
	2, // 0: wiki.v1.PageRevisionCreated.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: wiki.v1.PageAclChanged.perms:type_name -> wiki.v1.PermissionSnapshot
	2, // 2: wiki.v1.PageAclChanged.created_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wiki_v1_events_proto_init() }
func file_wiki_v1_events_proto_init() {
	if File_wiki_v1_events_proto != nil {
		return
	}
	file_wiki_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wiki_v1_events_proto_rawDesc), len(file_wiki_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wiki_v1_events_proto_goTypes,
		DependencyIndexes: file_wiki_v1_events_proto_depIdxs,
		MessageInfos:      file_wiki_v1_events_proto_msgTypes,
	}.Build()
	File_wiki_v1_events_proto = out.File
	file_wiki_v1_events_proto_goTypes = nil
	file_wiki_v1_events_proto_depIdxs = nil
}
