// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: wiki/v1/messages.proto

// Wiki domain messages for write/read services and read model snapshots.

package wikiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PermissionSnapshot keeps a minimal snapshot of access rights.
type PermissionSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Roles allowed to view the page.
	AllowedRoles  []string `protobuf:"bytes,1,rep,name=allowed_roles,json=allowedRoles,proto3" json:"allowed_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionSnapshot) Reset() {
	*x = PermissionSnapshot{}
	mi := &file_wiki_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionSnapshot) ProtoMessage() {}

func (x *PermissionSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionSnapshot.ProtoReflect.Descriptor instead.
func (*PermissionSnapshot) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *PermissionSnapshot) GetAllowedRoles() []string {
	if x != nil {
		return x.AllowedRoles
	}
	return nil
}

// Page represents the canonical page aggregate.
type Page struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique page identifier.
	PageId string `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	// Space identifier.
	SpaceId string `protobuf:"bytes,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// URL-friendly slug.
	Slug string `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	// Page title.
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// Current head revision id.
	HeadRevisionId string `protobuf:"bytes,5,opt,name=head_revision_id,json=headRevisionId,proto3" json:"head_revision_id,omitempty"`
	// Creation timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_wiki_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Page) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *Page) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *Page) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Page) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Page) GetHeadRevisionId() string {
	if x != nil {
		return x.HeadRevisionId
	}
	return ""
}

func (x *Page) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Page) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Revision represents a page revision in the write model.
type Revision struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique revision identifier.
	RevisionId string `protobuf:"bytes,1,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	// Owning page id.
	PageId string `protobuf:"bytes,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	// Author user id.
	AuthorId string `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	// Base revision id for optimistic concurrency.
	BaseRevisionId string `protobuf:"bytes,4,opt,name=base_revision_id,json=baseRevisionId,proto3" json:"base_revision_id,omitempty"`
	// Markdown content.
	ContentMarkdown string `protobuf:"bytes,5,opt,name=content_markdown,json=contentMarkdown,proto3" json:"content_markdown,omitempty"`
	// Content hash for deduplication.
	ContentHash string `protobuf:"bytes,6,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	// Creation timestamp.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revision) Reset() {
	*x = Revision{}
	mi := &file_wiki_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revision) ProtoMessage() {}

func (x *Revision) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revision.ProtoReflect.Descriptor instead.
func (*Revision) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Revision) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *Revision) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *Revision) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Revision) GetBaseRevisionId() string {
	if x != nil {
		return x.BaseRevisionId
	}
	return ""
}

func (x *Revision) GetContentMarkdown() string {
	if x != nil {
		return x.ContentMarkdown
	}
	return ""
}

func (x *Revision) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *Revision) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// PageHead is a lightweight read-model pointer to the head revision.
type PageHead struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page id.
	PageId string `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	// Head revision id.
	HeadRevisionId string `protobuf:"bytes,2,opt,name=head_revision_id,json=headRevisionId,proto3" json:"head_revision_id,omitempty"`
	// Space id.
	SpaceId string `protobuf:"bytes,3,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// Page slug.
	Slug string `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	// Page title.
	Title string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	// Snapshot of permissions.
	Perms *PermissionSnapshot `protobuf:"bytes,6,opt,name=perms,proto3" json:"perms,omitempty"`
	// Last update timestamp.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageHead) Reset() {
	*x = PageHead{}
	mi := &file_wiki_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageHead) ProtoMessage() {}

func (x *PageHead) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageHead.ProtoReflect.Descriptor instead.
func (*PageHead) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *PageHead) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *PageHead) GetHeadRevisionId() string {
	if x != nil {
		return x.HeadRevisionId
	}
	return ""
}

func (x *PageHead) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *PageHead) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *PageHead) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PageHead) GetPerms() *PermissionSnapshot {
	if x != nil {
		return x.Perms
	}
	return nil
}

func (x *PageHead) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// PageSnapshot is an immutable rendered snapshot for fast reads.
type PageSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page id.
	PageId string `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	// Revision id.
	RevisionId string `protobuf:"bytes,2,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	// Space id.
	SpaceId string `protobuf:"bytes,3,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// Page slug.
	Slug string `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	// Page title.
	Title string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	// Rendered HTML.
	Html string `protobuf:"bytes,6,opt,name=html,proto3" json:"html,omitempty"`
	// Table of contents (serialized).
	Toc string `protobuf:"bytes,7,opt,name=toc,proto3" json:"toc,omitempty"`
	// Short summary.
	Summary string `protobuf:"bytes,8,opt,name=summary,proto3" json:"summary,omitempty"`
	// Word count.
	WordCount int32 `protobuf:"varint,9,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	// Snapshot creation timestamp.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageSnapshot) Reset() {
	*x = PageSnapshot{}
	mi := &file_wiki_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageSnapshot) ProtoMessage() {}

func (x *PageSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageSnapshot.ProtoReflect.Descriptor instead.
func (*PageSnapshot) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *PageSnapshot) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *PageSnapshot) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *PageSnapshot) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *PageSnapshot) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *PageSnapshot) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PageSnapshot) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *PageSnapshot) GetToc() string {
	if x != nil {
		return x.Toc
	}
	return ""
}

func (x *PageSnapshot) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PageSnapshot) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *PageSnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Request to create a new page with the initial revision.
type CreatePageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Space id where the page lives.
	SpaceId string `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// Slug for the new page.
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	// Title for the new page.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Markdown content.
	ContentMarkdown string `protobuf:"bytes,4,opt,name=content_markdown,json=contentMarkdown,proto3" json:"content_markdown,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePageRequest) Reset() {
	*x = CreatePageRequest{}
	mi := &file_wiki_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePageRequest) ProtoMessage() {}

func (x *CreatePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePageRequest.ProtoReflect.Descriptor instead.
func (*CreatePageRequest) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePageRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *CreatePageRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreatePageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePageRequest) GetContentMarkdown() string {
	if x != nil {
		return x.ContentMarkdown
	}
	return ""
}

// Response for create page.
type CreatePageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Newly created page id.
	PageId string `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	// Newly created revision id.
	RevisionId    string `protobuf:"bytes,2,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePageResponse) Reset() {
	*x = CreatePageResponse{}
	mi := &file_wiki_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePageResponse) ProtoMessage() {}

func (x *CreatePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePageResponse.ProtoReflect.Descriptor instead.
func (*CreatePageResponse) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePageResponse) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *CreatePageResponse) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

// Request to create a new revision for a page.
type CreateRevisionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target page id.
	PageId string `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	// Base revision id for concurrency control.
	BaseRevisionId string `protobuf:"bytes,2,opt,name=base_revision_id,json=baseRevisionId,proto3" json:"base_revision_id,omitempty"`
	// Markdown content.
	ContentMarkdown string `protobuf:"bytes,3,opt,name=content_markdown,json=contentMarkdown,proto3" json:"content_markdown,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateRevisionRequest) Reset() {
	*x = CreateRevisionRequest{}
	mi := &file_wiki_v1_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRevisionRequest) ProtoMessage() {}

func (x *CreateRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRevisionRequest.ProtoReflect.Descriptor instead.
func (*CreateRevisionRequest) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRevisionRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *CreateRevisionRequest) GetBaseRevisionId() string {
	if x != nil {
		return x.BaseRevisionId
	}
	return ""
}

func (x *CreateRevisionRequest) GetContentMarkdown() string {
	if x != nil {
		return x.ContentMarkdown
	}
	return ""
}

// Response with created revision id.
type CreateRevisionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New revision id.
	RevisionId    string `protobuf:"bytes,1,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRevisionResponse) Reset() {
	*x = CreateRevisionResponse{}
	mi := &file_wiki_v1_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRevisionResponse) ProtoMessage() {}

func (x *CreateRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRevisionResponse.ProtoReflect.Descriptor instead.
func (*CreateRevisionResponse) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRevisionResponse) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

// Request to delete a page.
type DeletePageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page id to delete.
	PageId        string `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePageRequest) Reset() {
	*x = DeletePageRequest{}
	mi := &file_wiki_v1_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePageRequest) ProtoMessage() {}

func (x *DeletePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePageRequest.ProtoReflect.Descriptor instead.
func (*DeletePageRequest) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePageRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

// Response for delete page.
type DeletePageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePageResponse) Reset() {
	*x = DeletePageResponse{}
	mi := &file_wiki_v1_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePageResponse) ProtoMessage() {}

func (x *DeletePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePageResponse.ProtoReflect.Descriptor instead.
func (*DeletePageResponse) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{10}
}

// Request to update ACL snapshot for a page.
type SetPageAclRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page id to update.
	PageId string `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	// Updated permission snapshot.
	Perms         *PermissionSnapshot `protobuf:"bytes,2,opt,name=perms,proto3" json:"perms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPageAclRequest) Reset() {
	*x = SetPageAclRequest{}
	mi := &file_wiki_v1_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPageAclRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPageAclRequest) ProtoMessage() {}

func (x *SetPageAclRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPageAclRequest.ProtoReflect.Descriptor instead.
func (*SetPageAclRequest) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *SetPageAclRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *SetPageAclRequest) GetPerms() *PermissionSnapshot {
	if x != nil {
		return x.Perms
	}
	return nil
}

// Response for ACL update.
type SetPageAclResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPageAclResponse) Reset() {
	*x = SetPageAclResponse{}
	mi := &file_wiki_v1_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPageAclResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPageAclResponse) ProtoMessage() {}

func (x *SetPageAclResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPageAclResponse.ProtoReflect.Descriptor instead.
func (*SetPageAclResponse) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{12}
}

// Request to fetch the head pointer.
type GetPageHeadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page id.
	PageId        string `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageHeadRequest) Reset() {
	*x = GetPageHeadRequest{}
	mi := &file_wiki_v1_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageHeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageHeadRequest) ProtoMessage() {}

func (x *GetPageHeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageHeadRequest.ProtoReflect.Descriptor instead.
func (*GetPageHeadRequest) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *GetPageHeadRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

// Response with head pointer.
type GetPageHeadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Head pointer.
	Head          *PageHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageHeadResponse) Reset() {
	*x = GetPageHeadResponse{}
	mi := &file_wiki_v1_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageHeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageHeadResponse) ProtoMessage() {}

func (x *GetPageHeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageHeadResponse.ProtoReflect.Descriptor instead.
func (*GetPageHeadResponse) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *GetPageHeadResponse) GetHead() *PageHead {
	if x != nil {
		return x.Head
	}
	return nil
}

// Request to fetch a snapshot by revision id.
type GetPageSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page id.
	PageId string `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	// Revision id.
	RevisionId    string `protobuf:"bytes,2,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageSnapshotRequest) Reset() {
	*x = GetPageSnapshotRequest{}
	mi := &file_wiki_v1_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageSnapshotRequest) ProtoMessage() {}

func (x *GetPageSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetPageSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{15}
}

func (x *GetPageSnapshotRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *GetPageSnapshotRequest) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

// Response with a page snapshot.
type GetPageSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Snapshot payload.
	Snapshot      *PageSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageSnapshotResponse) Reset() {
	*x = GetPageSnapshotResponse{}
	mi := &file_wiki_v1_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageSnapshotResponse) ProtoMessage() {}

func (x *GetPageSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetPageSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{16}
}

func (x *GetPageSnapshotResponse) GetSnapshot() *PageSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// Request to fetch a page by slug.
type GetPageBySlugRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Space id.
	SpaceId string `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// Page slug.
	Slug          string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageBySlugRequest) Reset() {
	*x = GetPageBySlugRequest{}
	mi := &file_wiki_v1_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageBySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageBySlugRequest) ProtoMessage() {}

func (x *GetPageBySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageBySlugRequest.ProtoReflect.Descriptor instead.
func (*GetPageBySlugRequest) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{17}
}

func (x *GetPageBySlugRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *GetPageBySlugRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

// Response with snapshot resolved by slug.
type GetPageBySlugResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Snapshot payload.
	Snapshot      *PageSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageBySlugResponse) Reset() {
	*x = GetPageBySlugResponse{}
	mi := &file_wiki_v1_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageBySlugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageBySlugResponse) ProtoMessage() {}

func (x *GetPageBySlugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageBySlugResponse.ProtoReflect.Descriptor instead.
func (*GetPageBySlugResponse) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{18}
}

func (x *GetPageBySlugResponse) GetSnapshot() *PageSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// Request to list pages in a space.
type ListPagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Space id.
	SpaceId string `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// Maximum number of items.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Pagination token.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPagesRequest) Reset() {
	*x = ListPagesRequest{}
	mi := &file_wiki_v1_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPagesRequest) ProtoMessage() {}

func (x *ListPagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPagesRequest.ProtoReflect.Descriptor instead.
func (*ListPagesRequest) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{19}
}

func (x *ListPagesRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *ListPagesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPagesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Response with page heads and pagination data.
type ListPagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page head entries.
	Pages []*PageHead `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	// Pagination token.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPagesResponse) Reset() {
	*x = ListPagesResponse{}
	mi := &file_wiki_v1_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPagesResponse) ProtoMessage() {}

func (x *ListPagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wiki_v1_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPagesResponse.ProtoReflect.Descriptor instead.
func (*ListPagesResponse) Descriptor() ([]byte, []int) {
	return file_wiki_v1_messages_proto_rawDescGZIP(), []int{20}
}

func (x *ListPagesResponse) GetPages() []*PageHead {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *ListPagesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_wiki_v1_messages_proto protoreflect.FileDescriptor

const file_wiki_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x16wiki/v1/messages.proto\x12\awiki.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n" +
	"\x12PermissionSnapshot\x12#\n" +
	"\rallowed_roles\x18\x01 \x03(\tR\fallowedRoles\"\x84\x02\n" +
	"\x04Page\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x19\n" +
	"\bspace_id\x18\x02 \x01(\tR\aspaceId\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12(\n" +
	"\x10head_revision_id\x18\x05 \x01(\tR\x0eheadRevisionId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x94\x02\n" +
	"\bRevision\x12\x1f\n" +
	"\vrevision_id\x18\x01 \x01(\tR\n" +
	"revisionId\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\tR\x06pageId\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12(\n" +
	"\x10base_revision_id\x18\x04 \x01(\tR\x0ebaseRevisionId\x12)\n" +
	"\x10content_markdown\x18\x05 \x01(\tR\x0fcontentMarkdown\x12!\n" +
	"\fcontent_hash\x18\x06 \x01(\tR\vcontentHash\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x80\x02\n" +
	"\bPageHead\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12(\n" +
	"\x10head_revision_id\x18\x02 \x01(\tR\x0eheadRevisionId\x12\x19\n" +
	"\bspace_id\x18\x03 \x01(\tR\aspaceId\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x121\n" +
	"\x05perms\x18\x06 \x01(\v2\x1b.wiki.v1.PermissionSnapshotR\x05perms\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa7\x02\n" +
	"\fPageSnapshot\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x1f\n" +
	"\vrevision_id\x18\x02 \x01(\tR\n" +
	"revisionId\x12\x19\n" +
	"\bspace_id\x18\x03 \x01(\tR\aspaceId\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04html\x18\x06 \x01(\tR\x04html\x12\x10\n" +
	"\x03toc\x18\a \x01(\tR\x03toc\x12\x18\n" +
	"\asummary\x18\b \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"word_count\x18\t \x01(\x05R\twordCount\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x83\x01\n" +
	"\x11CreatePageRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12)\n" +
	"\x10content_markdown\x18\x04 \x01(\tR\x0fcontentMarkdown\"N\n" +
	"\x12CreatePageResponse\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x1f\n" +
	"\vrevision_id\x18\x02 \x01(\tR\n" +
	"revisionId\"\x85\x01\n" +
	"\x15CreateRevisionRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12(\n" +
	"\x10base_revision_id\x18\x02 \x01(\tR\x0ebaseRevisionId\x12)\n" +
	"\x10content_markdown\x18\x03 \x01(\tR\x0fcontentMarkdown\"9\n" +
	"\x16CreateRevisionResponse\x12\x1f\n" +
	"\vrevision_id\x18\x01 \x01(\tR\n" +
	"revisionId\",\n" +
	"\x11DeletePageRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\"\x14\n" +
	"\x12DeletePageResponse\"_\n" +
	"\x11SetPageAclRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x121\n" +
	"\x05perms\x18\x02 \x01(\v2\x1b.wiki.v1.PermissionSnapshotR\x05perms\"\x14\n" +
	"\x12SetPageAclResponse\"-\n" +
	"\x12GetPageHeadRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\"<\n" +
	"\x13GetPageHeadResponse\x12%\n" +
	"\x04head\x18\x01 \x01(\v2\x11.wiki.v1.PageHeadR\x04head\"R\n" +
	"\x16GetPageSnapshotRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x1f\n" +
	"\vrevision_id\x18\x02 \x01(\tR\n" +
	"revisionId\"L\n" +
	"\x17GetPageSnapshotResponse\x121\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x15.wiki.v1.PageSnapshotR\bsnapshot\"E\n" +
	"\x14GetPageBySlugRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"J\n" +
	"\x15GetPageBySlugResponse\x121\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x15.wiki.v1.PageSnapshotR\bsnapshot\"i\n" +
	"\x10ListPagesRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"d\n" +
	"\x11ListPagesResponse\x12'\n" +
	"\x05pages\x18\x01 \x03(\v2\x11.wiki.v1.PageHeadR\x05pages\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageTokenB/Z-github.com/invenlore/proto/pkg/wiki/v1;wikiv1b\x06proto3"

var (
	file_wiki_v1_messages_proto_rawDescOnce sync.Once
	file_wiki_v1_messages_proto_rawDescData []byte
)

func file_wiki_v1_messages_proto_rawDescGZIP() []byte {
	file_wiki_v1_messages_proto_rawDescOnce.Do(func() {
		file_wiki_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wiki_v1_messages_proto_rawDesc), len(file_wiki_v1_messages_proto_rawDesc)))
	})
	return file_wiki_v1_messages_proto_rawDescData
}

var file_wiki_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_wiki_v1_messages_proto_goTypes = []any{
	(*PermissionSnapshot)(nil),      // 0: wiki.v1.PermissionSnapshot
	(*Page)(nil),                    // 1: wiki.v1.Page
	(*Revision)(nil),                // 2: wiki.v1.Revision
	(*PageHead)(nil),                // 3: wiki.v1.PageHead
	(*PageSnapshot)(nil),            // 4: wiki.v1.PageSnapshot
	(*CreatePageRequest)(nil),       // 5: wiki.v1.CreatePageRequest
	(*CreatePageResponse)(nil),      // 6: wiki.v1.CreatePageResponse
	(*CreateRevisionRequest)(nil),   // 7: wiki.v1.CreateRevisionRequest
	(*CreateRevisionResponse)(nil),  // 8: wiki.v1.CreateRevisionResponse
	(*DeletePageRequest)(nil),       // 9: wiki.v1.DeletePageRequest
	(*DeletePageResponse)(nil),      // 10: wiki.v1.DeletePageResponse
	(*SetPageAclRequest)(nil),       // 11: wiki.v1.SetPageAclRequest
	(*SetPageAclResponse)(nil),      // 12: wiki.v1.SetPageAclResponse
	(*GetPageHeadRequest)(nil),      // 13: wiki.v1.GetPageHeadRequest
	(*GetPageHeadResponse)(nil),     // 14: wiki.v1.GetPageHeadResponse
	(*GetPageSnapshotRequest)(nil),  // 15: wiki.v1.GetPageSnapshotRequest
	(*GetPageSnapshotResponse)(nil), // 16: wiki.v1.GetPageSnapshotResponse
	(*GetPageBySlugRequest)(nil),    // 17: wiki.v1.GetPageBySlugRequest
	(*GetPageBySlugResponse)(nil),   // 18: wiki.v1.GetPageBySlugResponse
	(*ListPagesRequest)(nil),        // 19: wiki.v1.ListPagesRequest
	(*ListPagesResponse)(nil),       // 20: wiki.v1.ListPagesResponse
	(*timestamppb.Timestamp)(nil),   // 21: google.protobuf.Timestamp
}
var file_wiki_v1_messages_proto_depIdxs = []int32{
	21, // 0: wiki.v1.Page.created_at:type_name -> google.protobuf.Timestamp
	21, // 1: wiki.v1.Page.updated_at:type_name -> google.protobuf.Timestamp
	21, // 2: wiki.v1.Revision.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: wiki.v1.PageHead.perms:type_name -> wiki.v1.PermissionSnapshot
	21, // 4: wiki.v1.PageHead.updated_at:type_name -> google.protobuf.Timestamp
	21, // 5: wiki.v1.PageSnapshot.created_at:type_name -> google.protobuf.Timestamp
	0,  // 6: wiki.v1.SetPageAclRequest.perms:type_name -> wiki.v1.PermissionSnapshot
	3,  // 7: wiki.v1.GetPageHeadResponse.head:type_name -> wiki.v1.PageHead
	4,  // 8: wiki.v1.GetPageSnapshotResponse.snapshot:type_name -> wiki.v1.PageSnapshot
	4,  // 9: wiki.v1.GetPageBySlugResponse.snapshot:type_name -> wiki.v1.PageSnapshot
	3,  // 10: wiki.v1.ListPagesResponse.pages:type_name -> wiki.v1.PageHead
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_wiki_v1_messages_proto_init() }
func file_wiki_v1_messages_proto_init() {
	if File_wiki_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wiki_v1_messages_proto_rawDesc), len(file_wiki_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wiki_v1_messages_proto_goTypes,
		DependencyIndexes: file_wiki_v1_messages_proto_depIdxs,
		MessageInfos:      file_wiki_v1_messages_proto_msgTypes,
	}.Build()
	File_wiki_v1_messages_proto = out.File
	file_wiki_v1_messages_proto_goTypes = nil
	file_wiki_v1_messages_proto_depIdxs = nil
}
