// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: wiki/v1/read_service.proto

// Wiki read APIs optimized for fast read model access.

package wikiv1

import (
	context "context"
	v1 "github.com/invenlore/proto/pkg/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WikiReadService_HealthCheck_FullMethodName     = "/wiki.v1.WikiReadService/HealthCheck"
	WikiReadService_GetPageHead_FullMethodName     = "/wiki.v1.WikiReadService/GetPageHead"
	WikiReadService_GetPageSnapshot_FullMethodName = "/wiki.v1.WikiReadService/GetPageSnapshot"
	WikiReadService_GetPageBySlug_FullMethodName   = "/wiki.v1.WikiReadService/GetPageBySlug"
	WikiReadService_ListPages_FullMethodName       = "/wiki.v1.WikiReadService/ListPages"
)

// WikiReadServiceClient is the client API for WikiReadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WikiReadService handles read operations for wiki pages.
type WikiReadServiceClient interface {
	// HealthCheck verifies service liveness.
	HealthCheck(ctx context.Context, in *v1.ServiceHealthRequest, opts ...grpc.CallOption) (*v1.ServiceHealthResponse, error)
	// GetPageHead returns the head pointer for a page.
	GetPageHead(ctx context.Context, in *GetPageHeadRequest, opts ...grpc.CallOption) (*GetPageHeadResponse, error)
	// GetPageSnapshot returns an immutable snapshot for a revision.
	GetPageSnapshot(ctx context.Context, in *GetPageSnapshotRequest, opts ...grpc.CallOption) (*GetPageSnapshotResponse, error)
	// GetPageBySlug resolves a page by slug within a space.
	GetPageBySlug(ctx context.Context, in *GetPageBySlugRequest, opts ...grpc.CallOption) (*GetPageBySlugResponse, error)
	// ListPages lists pages within a space with pagination.
	ListPages(ctx context.Context, in *ListPagesRequest, opts ...grpc.CallOption) (*ListPagesResponse, error)
}

type wikiReadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWikiReadServiceClient(cc grpc.ClientConnInterface) WikiReadServiceClient {
	return &wikiReadServiceClient{cc}
}

func (c *wikiReadServiceClient) HealthCheck(ctx context.Context, in *v1.ServiceHealthRequest, opts ...grpc.CallOption) (*v1.ServiceHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ServiceHealthResponse)
	err := c.cc.Invoke(ctx, WikiReadService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiReadServiceClient) GetPageHead(ctx context.Context, in *GetPageHeadRequest, opts ...grpc.CallOption) (*GetPageHeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPageHeadResponse)
	err := c.cc.Invoke(ctx, WikiReadService_GetPageHead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiReadServiceClient) GetPageSnapshot(ctx context.Context, in *GetPageSnapshotRequest, opts ...grpc.CallOption) (*GetPageSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPageSnapshotResponse)
	err := c.cc.Invoke(ctx, WikiReadService_GetPageSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiReadServiceClient) GetPageBySlug(ctx context.Context, in *GetPageBySlugRequest, opts ...grpc.CallOption) (*GetPageBySlugResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPageBySlugResponse)
	err := c.cc.Invoke(ctx, WikiReadService_GetPageBySlug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiReadServiceClient) ListPages(ctx context.Context, in *ListPagesRequest, opts ...grpc.CallOption) (*ListPagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPagesResponse)
	err := c.cc.Invoke(ctx, WikiReadService_ListPages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WikiReadServiceServer is the server API for WikiReadService service.
// All implementations must embed UnimplementedWikiReadServiceServer
// for forward compatibility.
//
// WikiReadService handles read operations for wiki pages.
type WikiReadServiceServer interface {
	// HealthCheck verifies service liveness.
	HealthCheck(context.Context, *v1.ServiceHealthRequest) (*v1.ServiceHealthResponse, error)
	// GetPageHead returns the head pointer for a page.
	GetPageHead(context.Context, *GetPageHeadRequest) (*GetPageHeadResponse, error)
	// GetPageSnapshot returns an immutable snapshot for a revision.
	GetPageSnapshot(context.Context, *GetPageSnapshotRequest) (*GetPageSnapshotResponse, error)
	// GetPageBySlug resolves a page by slug within a space.
	GetPageBySlug(context.Context, *GetPageBySlugRequest) (*GetPageBySlugResponse, error)
	// ListPages lists pages within a space with pagination.
	ListPages(context.Context, *ListPagesRequest) (*ListPagesResponse, error)
	mustEmbedUnimplementedWikiReadServiceServer()
}

// UnimplementedWikiReadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWikiReadServiceServer struct{}

func (UnimplementedWikiReadServiceServer) HealthCheck(context.Context, *v1.ServiceHealthRequest) (*v1.ServiceHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedWikiReadServiceServer) GetPageHead(context.Context, *GetPageHeadRequest) (*GetPageHeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPageHead not implemented")
}
func (UnimplementedWikiReadServiceServer) GetPageSnapshot(context.Context, *GetPageSnapshotRequest) (*GetPageSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPageSnapshot not implemented")
}
func (UnimplementedWikiReadServiceServer) GetPageBySlug(context.Context, *GetPageBySlugRequest) (*GetPageBySlugResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPageBySlug not implemented")
}
func (UnimplementedWikiReadServiceServer) ListPages(context.Context, *ListPagesRequest) (*ListPagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPages not implemented")
}
func (UnimplementedWikiReadServiceServer) mustEmbedUnimplementedWikiReadServiceServer() {}
func (UnimplementedWikiReadServiceServer) testEmbeddedByValue()                         {}

// UnsafeWikiReadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WikiReadServiceServer will
// result in compilation errors.
type UnsafeWikiReadServiceServer interface {
	mustEmbedUnimplementedWikiReadServiceServer()
}

func RegisterWikiReadServiceServer(s grpc.ServiceRegistrar, srv WikiReadServiceServer) {
	// If the following call panics, it indicates UnimplementedWikiReadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WikiReadService_ServiceDesc, srv)
}

func _WikiReadService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ServiceHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiReadServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiReadService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiReadServiceServer).HealthCheck(ctx, req.(*v1.ServiceHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiReadService_GetPageHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPageHeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiReadServiceServer).GetPageHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiReadService_GetPageHead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiReadServiceServer).GetPageHead(ctx, req.(*GetPageHeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiReadService_GetPageSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPageSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiReadServiceServer).GetPageSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiReadService_GetPageSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiReadServiceServer).GetPageSnapshot(ctx, req.(*GetPageSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiReadService_GetPageBySlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPageBySlugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiReadServiceServer).GetPageBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiReadService_GetPageBySlug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiReadServiceServer).GetPageBySlug(ctx, req.(*GetPageBySlugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiReadService_ListPages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiReadServiceServer).ListPages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiReadService_ListPages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiReadServiceServer).ListPages(ctx, req.(*ListPagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WikiReadService_ServiceDesc is the grpc.ServiceDesc for WikiReadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WikiReadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wiki.v1.WikiReadService",
	HandlerType: (*WikiReadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _WikiReadService_HealthCheck_Handler,
		},
		{
			MethodName: "GetPageHead",
			Handler:    _WikiReadService_GetPageHead_Handler,
		},
		{
			MethodName: "GetPageSnapshot",
			Handler:    _WikiReadService_GetPageSnapshot_Handler,
		},
		{
			MethodName: "GetPageBySlug",
			Handler:    _WikiReadService_GetPageBySlug_Handler,
		},
		{
			MethodName: "ListPages",
			Handler:    _WikiReadService_ListPages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wiki/v1/read_service.proto",
}
