// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: wiki/v1/read_service.proto

// Wiki read APIs optimized for fast read model access.

package wikiv1

import (
	v1 "github.com/invenlore/proto/pkg/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_wiki_v1_read_service_proto protoreflect.FileDescriptor

const file_wiki_v1_read_service_proto_rawDesc = "" +
	"\n" +
	"\x1awiki/v1/read_service.proto\x12\awiki.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x15common/v1/utils.proto\x1a\x16wiki/v1/messages.proto2\xd3\x04\n" +
	"\x0fWikiReadService\x12R\n" +
	"\vHealthCheck\x12\x1f.common.v1.ServiceHealthRequest\x1a .common.v1.ServiceHealthResponse\"\x00\x12j\n" +
	"\vGetPageHead\x12\x1b.wiki.v1.GetPageHeadRequest\x1a\x1c.wiki.v1.GetPageHeadResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/pages/{page_id}/head\x12\x92\x01\n" +
	"\x0fGetPageSnapshot\x12\x1f.wiki.v1.GetPageSnapshotRequest\x1a .wiki.v1.GetPageSnapshotResponse\"<\x82\xd3\xe4\x93\x026\x124/v1/pages/{page_id}/revisions/{revision_id}/snapshot\x12\x81\x01\n" +
	"\rGetPageBySlug\x12\x1d.wiki.v1.GetPageBySlugRequest\x1a\x1e.wiki.v1.GetPageBySlugResponse\"1\x82\xd3\xe4\x93\x02+\x12)/v1/spaces/{space_id}/pages:bySlug/{slug}\x12g\n" +
	"\tListPages\x12\x19.wiki.v1.ListPagesRequest\x1a\x1a.wiki.v1.ListPagesResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/spaces/{space_id}/pagesB/Z-github.com/invenlore/proto/pkg/wiki/v1;wikiv1b\x06proto3"

var file_wiki_v1_read_service_proto_goTypes = []any{
	(*v1.ServiceHealthRequest)(nil),  // 0: common.v1.ServiceHealthRequest
	(*GetPageHeadRequest)(nil),       // 1: wiki.v1.GetPageHeadRequest
	(*GetPageSnapshotRequest)(nil),   // 2: wiki.v1.GetPageSnapshotRequest
	(*GetPageBySlugRequest)(nil),     // 3: wiki.v1.GetPageBySlugRequest
	(*ListPagesRequest)(nil),         // 4: wiki.v1.ListPagesRequest
	(*v1.ServiceHealthResponse)(nil), // 5: common.v1.ServiceHealthResponse
	(*GetPageHeadResponse)(nil),      // 6: wiki.v1.GetPageHeadResponse
	(*GetPageSnapshotResponse)(nil),  // 7: wiki.v1.GetPageSnapshotResponse
	(*GetPageBySlugResponse)(nil),    // 8: wiki.v1.GetPageBySlugResponse
	(*ListPagesResponse)(nil),        // 9: wiki.v1.ListPagesResponse
}
var file_wiki_v1_read_service_proto_depIdxs = []int32{
	0, // 0: wiki.v1.WikiReadService.HealthCheck:input_type -> common.v1.ServiceHealthRequest
	1, // 1: wiki.v1.WikiReadService.GetPageHead:input_type -> wiki.v1.GetPageHeadRequest
	2, // 2: wiki.v1.WikiReadService.GetPageSnapshot:input_type -> wiki.v1.GetPageSnapshotRequest
	3, // 3: wiki.v1.WikiReadService.GetPageBySlug:input_type -> wiki.v1.GetPageBySlugRequest
	4, // 4: wiki.v1.WikiReadService.ListPages:input_type -> wiki.v1.ListPagesRequest
	5, // 5: wiki.v1.WikiReadService.HealthCheck:output_type -> common.v1.ServiceHealthResponse
	6, // 6: wiki.v1.WikiReadService.GetPageHead:output_type -> wiki.v1.GetPageHeadResponse
	7, // 7: wiki.v1.WikiReadService.GetPageSnapshot:output_type -> wiki.v1.GetPageSnapshotResponse
	8, // 8: wiki.v1.WikiReadService.GetPageBySlug:output_type -> wiki.v1.GetPageBySlugResponse
	9, // 9: wiki.v1.WikiReadService.ListPages:output_type -> wiki.v1.ListPagesResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wiki_v1_read_service_proto_init() }
func file_wiki_v1_read_service_proto_init() {
	if File_wiki_v1_read_service_proto != nil {
		return
	}
	file_wiki_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wiki_v1_read_service_proto_rawDesc), len(file_wiki_v1_read_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wiki_v1_read_service_proto_goTypes,
		DependencyIndexes: file_wiki_v1_read_service_proto_depIdxs,
	}.Build()
	File_wiki_v1_read_service_proto = out.File
	file_wiki_v1_read_service_proto_goTypes = nil
	file_wiki_v1_read_service_proto_depIdxs = nil
}
