// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: wiki/v1/write_service.proto

// Wiki write APIs for creating and mutating pages.

package wikiv1

import (
	v1 "github.com/invenlore/proto/pkg/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_wiki_v1_write_service_proto protoreflect.FileDescriptor

const file_wiki_v1_write_service_proto_rawDesc = "" +
	"\n" +
	"\x1bwiki/v1/write_service.proto\x12\awiki.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x15common/v1/utils.proto\x1a\x16wiki/v1/messages.proto2\xa1\x04\n" +
	"\x10WikiWriteService\x12R\n" +
	"\vHealthCheck\x12\x1f.common.v1.ServiceHealthRequest\x1a .common.v1.ServiceHealthResponse\"\x00\x12m\n" +
	"\n" +
	"CreatePage\x12\x1a.wiki.v1.CreatePageRequest\x1a\x1b.wiki.v1.CreatePageResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/spaces/{space_id}/pages\x12{\n" +
	"\x0eCreateRevision\x12\x1e.wiki.v1.CreateRevisionRequest\x1a\x1f.wiki.v1.CreateRevisionResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/pages/{page_id}/revisions\x12b\n" +
	"\n" +
	"DeletePage\x12\x1a.wiki.v1.DeletePageRequest\x1a\x1b.wiki.v1.DeletePageResponse\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/pages/{page_id}\x12i\n" +
	"\n" +
	"SetPageAcl\x12\x1a.wiki.v1.SetPageAclRequest\x1a\x1b.wiki.v1.SetPageAclResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/pages/{page_id}/aclB/Z-github.com/invenlore/proto/pkg/wiki/v1;wikiv1b\x06proto3"

var file_wiki_v1_write_service_proto_goTypes = []any{
	(*v1.ServiceHealthRequest)(nil),  // 0: common.v1.ServiceHealthRequest
	(*CreatePageRequest)(nil),        // 1: wiki.v1.CreatePageRequest
	(*CreateRevisionRequest)(nil),    // 2: wiki.v1.CreateRevisionRequest
	(*DeletePageRequest)(nil),        // 3: wiki.v1.DeletePageRequest
	(*SetPageAclRequest)(nil),        // 4: wiki.v1.SetPageAclRequest
	(*v1.ServiceHealthResponse)(nil), // 5: common.v1.ServiceHealthResponse
	(*CreatePageResponse)(nil),       // 6: wiki.v1.CreatePageResponse
	(*CreateRevisionResponse)(nil),   // 7: wiki.v1.CreateRevisionResponse
	(*DeletePageResponse)(nil),       // 8: wiki.v1.DeletePageResponse
	(*SetPageAclResponse)(nil),       // 9: wiki.v1.SetPageAclResponse
}
var file_wiki_v1_write_service_proto_depIdxs = []int32{
	0, // 0: wiki.v1.WikiWriteService.HealthCheck:input_type -> common.v1.ServiceHealthRequest
	1, // 1: wiki.v1.WikiWriteService.CreatePage:input_type -> wiki.v1.CreatePageRequest
	2, // 2: wiki.v1.WikiWriteService.CreateRevision:input_type -> wiki.v1.CreateRevisionRequest
	3, // 3: wiki.v1.WikiWriteService.DeletePage:input_type -> wiki.v1.DeletePageRequest
	4, // 4: wiki.v1.WikiWriteService.SetPageAcl:input_type -> wiki.v1.SetPageAclRequest
	5, // 5: wiki.v1.WikiWriteService.HealthCheck:output_type -> common.v1.ServiceHealthResponse
	6, // 6: wiki.v1.WikiWriteService.CreatePage:output_type -> wiki.v1.CreatePageResponse
	7, // 7: wiki.v1.WikiWriteService.CreateRevision:output_type -> wiki.v1.CreateRevisionResponse
	8, // 8: wiki.v1.WikiWriteService.DeletePage:output_type -> wiki.v1.DeletePageResponse
	9, // 9: wiki.v1.WikiWriteService.SetPageAcl:output_type -> wiki.v1.SetPageAclResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wiki_v1_write_service_proto_init() }
func file_wiki_v1_write_service_proto_init() {
	if File_wiki_v1_write_service_proto != nil {
		return
	}
	file_wiki_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wiki_v1_write_service_proto_rawDesc), len(file_wiki_v1_write_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wiki_v1_write_service_proto_goTypes,
		DependencyIndexes: file_wiki_v1_write_service_proto_depIdxs,
	}.Build()
	File_wiki_v1_write_service_proto = out.File
	file_wiki_v1_write_service_proto_goTypes = nil
	file_wiki_v1_write_service_proto_depIdxs = nil
}
