// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: wiki/v1/write_service.proto

// Wiki write APIs for creating and mutating pages.

package wikiv1

import (
	context "context"
	v1 "github.com/invenlore/proto/pkg/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WikiWriteService_HealthCheck_FullMethodName    = "/wiki.v1.WikiWriteService/HealthCheck"
	WikiWriteService_CreatePage_FullMethodName     = "/wiki.v1.WikiWriteService/CreatePage"
	WikiWriteService_CreateRevision_FullMethodName = "/wiki.v1.WikiWriteService/CreateRevision"
	WikiWriteService_DeletePage_FullMethodName     = "/wiki.v1.WikiWriteService/DeletePage"
	WikiWriteService_SetPageAcl_FullMethodName     = "/wiki.v1.WikiWriteService/SetPageAcl"
)

// WikiWriteServiceClient is the client API for WikiWriteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WikiWriteService handles write operations for wiki pages.
type WikiWriteServiceClient interface {
	// HealthCheck verifies service liveness.
	HealthCheck(ctx context.Context, in *v1.ServiceHealthRequest, opts ...grpc.CallOption) (*v1.ServiceHealthResponse, error)
	// CreatePage creates a new page and initial revision.
	CreatePage(ctx context.Context, in *CreatePageRequest, opts ...grpc.CallOption) (*CreatePageResponse, error)
	// CreateRevision creates a new revision for an existing page.
	CreateRevision(ctx context.Context, in *CreateRevisionRequest, opts ...grpc.CallOption) (*CreateRevisionResponse, error)
	// DeletePage removes a page (soft delete in write model).
	DeletePage(ctx context.Context, in *DeletePageRequest, opts ...grpc.CallOption) (*DeletePageResponse, error)
	// SetPageAcl updates access control snapshot for a page.
	SetPageAcl(ctx context.Context, in *SetPageAclRequest, opts ...grpc.CallOption) (*SetPageAclResponse, error)
}

type wikiWriteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWikiWriteServiceClient(cc grpc.ClientConnInterface) WikiWriteServiceClient {
	return &wikiWriteServiceClient{cc}
}

func (c *wikiWriteServiceClient) HealthCheck(ctx context.Context, in *v1.ServiceHealthRequest, opts ...grpc.CallOption) (*v1.ServiceHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ServiceHealthResponse)
	err := c.cc.Invoke(ctx, WikiWriteService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiWriteServiceClient) CreatePage(ctx context.Context, in *CreatePageRequest, opts ...grpc.CallOption) (*CreatePageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePageResponse)
	err := c.cc.Invoke(ctx, WikiWriteService_CreatePage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiWriteServiceClient) CreateRevision(ctx context.Context, in *CreateRevisionRequest, opts ...grpc.CallOption) (*CreateRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRevisionResponse)
	err := c.cc.Invoke(ctx, WikiWriteService_CreateRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiWriteServiceClient) DeletePage(ctx context.Context, in *DeletePageRequest, opts ...grpc.CallOption) (*DeletePageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePageResponse)
	err := c.cc.Invoke(ctx, WikiWriteService_DeletePage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wikiWriteServiceClient) SetPageAcl(ctx context.Context, in *SetPageAclRequest, opts ...grpc.CallOption) (*SetPageAclResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPageAclResponse)
	err := c.cc.Invoke(ctx, WikiWriteService_SetPageAcl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WikiWriteServiceServer is the server API for WikiWriteService service.
// All implementations must embed UnimplementedWikiWriteServiceServer
// for forward compatibility.
//
// WikiWriteService handles write operations for wiki pages.
type WikiWriteServiceServer interface {
	// HealthCheck verifies service liveness.
	HealthCheck(context.Context, *v1.ServiceHealthRequest) (*v1.ServiceHealthResponse, error)
	// CreatePage creates a new page and initial revision.
	CreatePage(context.Context, *CreatePageRequest) (*CreatePageResponse, error)
	// CreateRevision creates a new revision for an existing page.
	CreateRevision(context.Context, *CreateRevisionRequest) (*CreateRevisionResponse, error)
	// DeletePage removes a page (soft delete in write model).
	DeletePage(context.Context, *DeletePageRequest) (*DeletePageResponse, error)
	// SetPageAcl updates access control snapshot for a page.
	SetPageAcl(context.Context, *SetPageAclRequest) (*SetPageAclResponse, error)
	mustEmbedUnimplementedWikiWriteServiceServer()
}

// UnimplementedWikiWriteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWikiWriteServiceServer struct{}

func (UnimplementedWikiWriteServiceServer) HealthCheck(context.Context, *v1.ServiceHealthRequest) (*v1.ServiceHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedWikiWriteServiceServer) CreatePage(context.Context, *CreatePageRequest) (*CreatePageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePage not implemented")
}
func (UnimplementedWikiWriteServiceServer) CreateRevision(context.Context, *CreateRevisionRequest) (*CreateRevisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRevision not implemented")
}
func (UnimplementedWikiWriteServiceServer) DeletePage(context.Context, *DeletePageRequest) (*DeletePageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePage not implemented")
}
func (UnimplementedWikiWriteServiceServer) SetPageAcl(context.Context, *SetPageAclRequest) (*SetPageAclResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPageAcl not implemented")
}
func (UnimplementedWikiWriteServiceServer) mustEmbedUnimplementedWikiWriteServiceServer() {}
func (UnimplementedWikiWriteServiceServer) testEmbeddedByValue()                          {}

// UnsafeWikiWriteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WikiWriteServiceServer will
// result in compilation errors.
type UnsafeWikiWriteServiceServer interface {
	mustEmbedUnimplementedWikiWriteServiceServer()
}

func RegisterWikiWriteServiceServer(s grpc.ServiceRegistrar, srv WikiWriteServiceServer) {
	// If the following call panics, it indicates UnimplementedWikiWriteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WikiWriteService_ServiceDesc, srv)
}

func _WikiWriteService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ServiceHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiWriteServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiWriteService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiWriteServiceServer).HealthCheck(ctx, req.(*v1.ServiceHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiWriteService_CreatePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiWriteServiceServer).CreatePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiWriteService_CreatePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiWriteServiceServer).CreatePage(ctx, req.(*CreatePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiWriteService_CreateRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiWriteServiceServer).CreateRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiWriteService_CreateRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiWriteServiceServer).CreateRevision(ctx, req.(*CreateRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiWriteService_DeletePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiWriteServiceServer).DeletePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiWriteService_DeletePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiWriteServiceServer).DeletePage(ctx, req.(*DeletePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WikiWriteService_SetPageAcl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPageAclRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WikiWriteServiceServer).SetPageAcl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WikiWriteService_SetPageAcl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WikiWriteServiceServer).SetPageAcl(ctx, req.(*SetPageAclRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WikiWriteService_ServiceDesc is the grpc.ServiceDesc for WikiWriteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WikiWriteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wiki.v1.WikiWriteService",
	HandlerType: (*WikiWriteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _WikiWriteService_HealthCheck_Handler,
		},
		{
			MethodName: "CreatePage",
			Handler:    _WikiWriteService_CreatePage_Handler,
		},
		{
			MethodName: "CreateRevision",
			Handler:    _WikiWriteService_CreateRevision_Handler,
		},
		{
			MethodName: "DeletePage",
			Handler:    _WikiWriteService_DeletePage_Handler,
		},
		{
			MethodName: "SetPageAcl",
			Handler:    _WikiWriteService_SetPageAcl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wiki/v1/write_service.proto",
}
