// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: search/v1/messages.proto

// Search domain messages used for search and suggestions.

package searchv1

import (
	v1 "github.com/invenlore/proto/pkg/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchHit describes a single search result.
type SearchHit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page id.
	PageId string `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	// Space id.
	SpaceId string `protobuf:"bytes,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// Page title.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Page slug.
	Slug string `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	// Highlighted snippet.
	Snippet       string `protobuf:"bytes,5,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_search_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_search_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SearchHit) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *SearchHit) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *SearchHit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchHit) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SearchHit) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

// SearchRequest contains full-text query and filters.
type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query string.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Optional space filter.
	SpaceId string `protobuf:"bytes,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	// Pagination settings.
	Page          *v1.PageRequest `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *SearchRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// SearchResponse returns hits and pagination metadata.
type SearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matching documents.
	Hits []*SearchHit `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	// Pagination info.
	Page          *v1.PageResponse `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_search_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_search_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// SuggestRequest contains prefix for autocomplete.
type SuggestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prefix input.
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Optional space filter.
	SpaceId       string `protobuf:"bytes,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestRequest) Reset() {
	*x = SuggestRequest{}
	mi := &file_search_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestRequest) ProtoMessage() {}

func (x *SuggestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestRequest.ProtoReflect.Descriptor instead.
func (*SuggestRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *SuggestRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *SuggestRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

// SuggestResponse returns suggestions for prefix.
type SuggestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Suggested tokens.
	Suggestions   []string `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestResponse) Reset() {
	*x = SuggestResponse{}
	mi := &file_search_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestResponse) ProtoMessage() {}

func (x *SuggestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestResponse.ProtoReflect.Descriptor instead.
func (*SuggestResponse) Descriptor() ([]byte, []int) {
	return file_search_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *SuggestResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

var File_search_v1_messages_proto protoreflect.FileDescriptor

const file_search_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x18search/v1/messages.proto\x12\tsearch.v1\x1a\x1acommon/v1/pagination.proto\"\x83\x01\n" +
	"\tSearchHit\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x19\n" +
	"\bspace_id\x18\x02 \x01(\tR\aspaceId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x18\n" +
	"\asnippet\x18\x05 \x01(\tR\asnippet\"l\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x19\n" +
	"\bspace_id\x18\x02 \x01(\tR\aspaceId\x12*\n" +
	"\x04page\x18\x03 \x01(\v2\x16.common.v1.PageRequestR\x04page\"g\n" +
	"\x0eSearchResponse\x12(\n" +
	"\x04hits\x18\x01 \x03(\v2\x14.search.v1.SearchHitR\x04hits\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.common.v1.PageResponseR\x04page\"C\n" +
	"\x0eSuggestRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x19\n" +
	"\bspace_id\x18\x02 \x01(\tR\aspaceId\"3\n" +
	"\x0fSuggestResponse\x12 \n" +
	"\vsuggestions\x18\x01 \x03(\tR\vsuggestionsB3Z1github.com/invenlore/proto/pkg/search/v1;searchv1b\x06proto3"

var (
	file_search_v1_messages_proto_rawDescOnce sync.Once
	file_search_v1_messages_proto_rawDescData []byte
)

func file_search_v1_messages_proto_rawDescGZIP() []byte {
	file_search_v1_messages_proto_rawDescOnce.Do(func() {
		file_search_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_v1_messages_proto_rawDesc), len(file_search_v1_messages_proto_rawDesc)))
	})
	return file_search_v1_messages_proto_rawDescData
}

var file_search_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_search_v1_messages_proto_goTypes = []any{
	(*SearchHit)(nil),       // 0: search.v1.SearchHit
	(*SearchRequest)(nil),   // 1: search.v1.SearchRequest
	(*SearchResponse)(nil),  // 2: search.v1.SearchResponse
	(*SuggestRequest)(nil),  // 3: search.v1.SuggestRequest
	(*SuggestResponse)(nil), // 4: search.v1.SuggestResponse
	(*v1.PageRequest)(nil),  // 5: common.v1.PageRequest
	(*v1.PageResponse)(nil), // 6: common.v1.PageResponse
}
var file_search_v1_messages_proto_depIdxs = []int32{
	5, // 0: search.v1.SearchRequest.page:type_name -> common.v1.PageRequest
	0, // 1: search.v1.SearchResponse.hits:type_name -> search.v1.SearchHit
	6, // 2: search.v1.SearchResponse.page:type_name -> common.v1.PageResponse
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_search_v1_messages_proto_init() }
func file_search_v1_messages_proto_init() {
	if File_search_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_v1_messages_proto_rawDesc), len(file_search_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_search_v1_messages_proto_goTypes,
		DependencyIndexes: file_search_v1_messages_proto_depIdxs,
		MessageInfos:      file_search_v1_messages_proto_msgTypes,
	}.Build()
	File_search_v1_messages_proto = out.File
	file_search_v1_messages_proto_goTypes = nil
	file_search_v1_messages_proto_depIdxs = nil
}
