// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: search/v1/service.proto

// Search APIs exposed via gateway.

package searchv1

import (
	v1 "github.com/invenlore/proto/pkg/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_search_v1_service_proto protoreflect.FileDescriptor

const file_search_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x17search/v1/service.proto\x12\tsearch.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x15common/v1/utils.proto\x1a\x18search/v1/messages.proto2\x94\x02\n" +
	"\rSearchService\x12R\n" +
	"\vHealthCheck\x12\x1f.common.v1.ServiceHealthRequest\x1a .common.v1.ServiceHealthResponse\"\x00\x12Q\n" +
	"\x06Search\x12\x18.search.v1.SearchRequest\x1a\x19.search.v1.SearchResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/search\x12\\\n" +
	"\aSuggest\x12\x19.search.v1.SuggestRequest\x1a\x1a.search.v1.SuggestResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/search:suggestB3Z1github.com/invenlore/proto/pkg/search/v1;searchv1b\x06proto3"

var file_search_v1_service_proto_goTypes = []any{
	(*v1.ServiceHealthRequest)(nil),  // 0: common.v1.ServiceHealthRequest
	(*SearchRequest)(nil),            // 1: search.v1.SearchRequest
	(*SuggestRequest)(nil),           // 2: search.v1.SuggestRequest
	(*v1.ServiceHealthResponse)(nil), // 3: common.v1.ServiceHealthResponse
	(*SearchResponse)(nil),           // 4: search.v1.SearchResponse
	(*SuggestResponse)(nil),          // 5: search.v1.SuggestResponse
}
var file_search_v1_service_proto_depIdxs = []int32{
	0, // 0: search.v1.SearchService.HealthCheck:input_type -> common.v1.ServiceHealthRequest
	1, // 1: search.v1.SearchService.Search:input_type -> search.v1.SearchRequest
	2, // 2: search.v1.SearchService.Suggest:input_type -> search.v1.SuggestRequest
	3, // 3: search.v1.SearchService.HealthCheck:output_type -> common.v1.ServiceHealthResponse
	4, // 4: search.v1.SearchService.Search:output_type -> search.v1.SearchResponse
	5, // 5: search.v1.SearchService.Suggest:output_type -> search.v1.SuggestResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_search_v1_service_proto_init() }
func file_search_v1_service_proto_init() {
	if File_search_v1_service_proto != nil {
		return
	}
	file_search_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_v1_service_proto_rawDesc), len(file_search_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_v1_service_proto_goTypes,
		DependencyIndexes: file_search_v1_service_proto_depIdxs,
	}.Build()
	File_search_v1_service_proto = out.File
	file_search_v1_service_proto_goTypes = nil
	file_search_v1_service_proto_depIdxs = nil
}
