flowchart TB
  subgraph Node
    GW[api.gateway]
    ID[identity]
    WR[wiki-write]
    RD[wiki-read]
    MED[media]
    WORK[workers]
    MONGO[(Mongo)]
    REDIS[(Redis)]
  end
  S3[(Yandex S3)]
  OS[(OpenSearch)]

  MED --> S3
  WORK --> S3
  WORK --> OS
