// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: media/v1/events.proto

// Media outbox event payloads.

package mediav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MediaUploaded is emitted when an upload is finalized.
type MediaUploaded struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Media id.
	MediaId       string `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaUploaded) Reset() {
	*x = MediaUploaded{}
	mi := &file_media_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaUploaded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaUploaded) ProtoMessage() {}

func (x *MediaUploaded) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaUploaded.ProtoReflect.Descriptor instead.
func (*MediaUploaded) Descriptor() ([]byte, []int) {
	return file_media_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *MediaUploaded) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

var File_media_v1_events_proto protoreflect.FileDescriptor

const file_media_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x15media/v1/events.proto\x12\bmedia.v1\"*\n" +
	"\rMediaUploaded\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaIdB1Z/github.com/invenlore/proto/pkg/media/v1;mediav1b\x06proto3"

var (
	file_media_v1_events_proto_rawDescOnce sync.Once
	file_media_v1_events_proto_rawDescData []byte
)

func file_media_v1_events_proto_rawDescGZIP() []byte {
	file_media_v1_events_proto_rawDescOnce.Do(func() {
		file_media_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_v1_events_proto_rawDesc), len(file_media_v1_events_proto_rawDesc)))
	})
	return file_media_v1_events_proto_rawDescData
}

var file_media_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_media_v1_events_proto_goTypes = []any{
	(*MediaUploaded)(nil), // 0: media.v1.MediaUploaded
}
var file_media_v1_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_media_v1_events_proto_init() }
func file_media_v1_events_proto_init() {
	if File_media_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_v1_events_proto_rawDesc), len(file_media_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_v1_events_proto_goTypes,
		DependencyIndexes: file_media_v1_events_proto_depIdxs,
		MessageInfos:      file_media_v1_events_proto_msgTypes,
	}.Build()
	File_media_v1_events_proto = out.File
	file_media_v1_events_proto_goTypes = nil
	file_media_v1_events_proto_depIdxs = nil
}
