// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: media/v1/messages.proto

// Media domain messages for presigned upload/download workflows.

package mediav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MediaObject represents stored media metadata.
type MediaObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Media identifier.
	MediaId string `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	// Owner user id.
	OwnerId string `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// MIME content type.
	ContentType string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Object size in bytes.
	SizeBytes int64 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// SHA-256 checksum.
	Sha256 string `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// Creation timestamp.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaObject) Reset() {
	*x = MediaObject{}
	mi := &file_media_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaObject) ProtoMessage() {}

func (x *MediaObject) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaObject.ProtoReflect.Descriptor instead.
func (*MediaObject) Descriptor() ([]byte, []int) {
	return file_media_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *MediaObject) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *MediaObject) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *MediaObject) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MediaObject) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *MediaObject) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *MediaObject) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Request to initiate an upload.
type CreateUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MIME type of the uploaded file.
	ContentType string `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Size of the file in bytes.
	SizeBytes int64 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// SHA-256 checksum.
	Sha256        string `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadRequest) Reset() {
	*x = CreateUploadRequest{}
	mi := &file_media_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadRequest) ProtoMessage() {}

func (x *CreateUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadRequest.ProtoReflect.Descriptor instead.
func (*CreateUploadRequest) Descriptor() ([]byte, []int) {
	return file_media_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreateUploadRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreateUploadRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

// Response with presigned upload URL.
type CreateUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Media id reserved for the upload.
	MediaId string `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	// Presigned upload URL.
	UploadUrl string `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	// Additional required headers for the upload.
	RequiredHeaders map[string]string `protobuf:"bytes,3,rep,name=required_headers,json=requiredHeaders,proto3" json:"required_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Presign expiration in seconds.
	ExpiresInSeconds int64 `protobuf:"varint,4,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateUploadResponse) Reset() {
	*x = CreateUploadResponse{}
	mi := &file_media_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadResponse) ProtoMessage() {}

func (x *CreateUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadResponse.ProtoReflect.Descriptor instead.
func (*CreateUploadResponse) Descriptor() ([]byte, []int) {
	return file_media_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUploadResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *CreateUploadResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *CreateUploadResponse) GetRequiredHeaders() map[string]string {
	if x != nil {
		return x.RequiredHeaders
	}
	return nil
}

func (x *CreateUploadResponse) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

// Request to finalize an upload.
type FinalizeUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Media id to finalize.
	MediaId       string `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeUploadRequest) Reset() {
	*x = FinalizeUploadRequest{}
	mi := &file_media_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeUploadRequest) ProtoMessage() {}

func (x *FinalizeUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeUploadRequest.ProtoReflect.Descriptor instead.
func (*FinalizeUploadRequest) Descriptor() ([]byte, []int) {
	return file_media_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *FinalizeUploadRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

// Response with stored media metadata.
type FinalizeUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *MediaObject           `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeUploadResponse) Reset() {
	*x = FinalizeUploadResponse{}
	mi := &file_media_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeUploadResponse) ProtoMessage() {}

func (x *FinalizeUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeUploadResponse.ProtoReflect.Descriptor instead.
func (*FinalizeUploadResponse) Descriptor() ([]byte, []int) {
	return file_media_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *FinalizeUploadResponse) GetMedia() *MediaObject {
	if x != nil {
		return x.Media
	}
	return nil
}

// Request to fetch a presigned download URL.
type GetDownloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Media id to download.
	MediaId       string `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadRequest) Reset() {
	*x = GetDownloadRequest{}
	mi := &file_media_v1_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadRequest) ProtoMessage() {}

func (x *GetDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadRequest) Descriptor() ([]byte, []int) {
	return file_media_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetDownloadRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

// Response with presigned download URL.
type GetDownloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Presigned download URL.
	DownloadUrl string `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	// Presign expiration in seconds.
	ExpiresInSeconds int64 `protobuf:"varint,2,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetDownloadResponse) Reset() {
	*x = GetDownloadResponse{}
	mi := &file_media_v1_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadResponse) ProtoMessage() {}

func (x *GetDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadResponse) Descriptor() ([]byte, []int) {
	return file_media_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetDownloadResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *GetDownloadResponse) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

var File_media_v1_messages_proto protoreflect.FileDescriptor

const file_media_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x17media/v1/messages.proto\x12\bmedia.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x01\n" +
	"\vMediaObject\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"o\n" +
	"\x13CreateUploadRequest\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\"\xa2\x02\n" +
	"\x14CreateUploadResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12^\n" +
	"\x10required_headers\x18\x03 \x03(\v23.media.v1.CreateUploadResponse.RequiredHeadersEntryR\x0frequiredHeaders\x12,\n" +
	"\x12expires_in_seconds\x18\x04 \x01(\x03R\x10expiresInSeconds\x1aB\n" +
	"\x14RequiredHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\x15FinalizeUploadRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\"E\n" +
	"\x16FinalizeUploadResponse\x12+\n" +
	"\x05media\x18\x01 \x01(\v2\x15.media.v1.MediaObjectR\x05media\"/\n" +
	"\x12GetDownloadRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\"f\n" +
	"\x13GetDownloadResponse\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\x12,\n" +
	"\x12expires_in_seconds\x18\x02 \x01(\x03R\x10expiresInSecondsB1Z/github.com/invenlore/proto/pkg/media/v1;mediav1b\x06proto3"

var (
	file_media_v1_messages_proto_rawDescOnce sync.Once
	file_media_v1_messages_proto_rawDescData []byte
)

func file_media_v1_messages_proto_rawDescGZIP() []byte {
	file_media_v1_messages_proto_rawDescOnce.Do(func() {
		file_media_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_v1_messages_proto_rawDesc), len(file_media_v1_messages_proto_rawDesc)))
	})
	return file_media_v1_messages_proto_rawDescData
}

var file_media_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_media_v1_messages_proto_goTypes = []any{
	(*MediaObject)(nil),            // 0: media.v1.MediaObject
	(*CreateUploadRequest)(nil),    // 1: media.v1.CreateUploadRequest
	(*CreateUploadResponse)(nil),   // 2: media.v1.CreateUploadResponse
	(*FinalizeUploadRequest)(nil),  // 3: media.v1.FinalizeUploadRequest
	(*FinalizeUploadResponse)(nil), // 4: media.v1.FinalizeUploadResponse
	(*GetDownloadRequest)(nil),     // 5: media.v1.GetDownloadRequest
	(*GetDownloadResponse)(nil),    // 6: media.v1.GetDownloadResponse
	nil,                            // 7: media.v1.CreateUploadResponse.RequiredHeadersEntry
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_media_v1_messages_proto_depIdxs = []int32{
	8, // 0: media.v1.MediaObject.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: media.v1.CreateUploadResponse.required_headers:type_name -> media.v1.CreateUploadResponse.RequiredHeadersEntry
	0, // 2: media.v1.FinalizeUploadResponse.media:type_name -> media.v1.MediaObject
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_media_v1_messages_proto_init() }
func file_media_v1_messages_proto_init() {
	if File_media_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_v1_messages_proto_rawDesc), len(file_media_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_v1_messages_proto_goTypes,
		DependencyIndexes: file_media_v1_messages_proto_depIdxs,
		MessageInfos:      file_media_v1_messages_proto_msgTypes,
	}.Build()
	File_media_v1_messages_proto = out.File
	file_media_v1_messages_proto_goTypes = nil
	file_media_v1_messages_proto_depIdxs = nil
}
