// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: media/v1/service.proto

// Media APIs for presigned upload/download workflows.

package mediav1

import (
	context "context"
	v1 "github.com/invenlore/proto/pkg/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaService_HealthCheck_FullMethodName    = "/media.v1.MediaService/HealthCheck"
	MediaService_CreateUpload_FullMethodName   = "/media.v1.MediaService/CreateUpload"
	MediaService_FinalizeUpload_FullMethodName = "/media.v1.MediaService/FinalizeUpload"
	MediaService_GetDownload_FullMethodName    = "/media.v1.MediaService/GetDownload"
)

// MediaServiceClient is the client API for MediaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MediaService handles media upload and download flows.
type MediaServiceClient interface {
	// HealthCheck verifies service liveness.
	HealthCheck(ctx context.Context, in *v1.ServiceHealthRequest, opts ...grpc.CallOption) (*v1.ServiceHealthResponse, error)
	// CreateUpload returns a presigned URL for uploading media.
	CreateUpload(ctx context.Context, in *CreateUploadRequest, opts ...grpc.CallOption) (*CreateUploadResponse, error)
	// FinalizeUpload validates uploaded media and persists metadata.
	FinalizeUpload(ctx context.Context, in *FinalizeUploadRequest, opts ...grpc.CallOption) (*FinalizeUploadResponse, error)
	// GetDownload returns a presigned URL for downloading media.
	GetDownload(ctx context.Context, in *GetDownloadRequest, opts ...grpc.CallOption) (*GetDownloadResponse, error)
}

type mediaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaServiceClient(cc grpc.ClientConnInterface) MediaServiceClient {
	return &mediaServiceClient{cc}
}

func (c *mediaServiceClient) HealthCheck(ctx context.Context, in *v1.ServiceHealthRequest, opts ...grpc.CallOption) (*v1.ServiceHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ServiceHealthResponse)
	err := c.cc.Invoke(ctx, MediaService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) CreateUpload(ctx context.Context, in *CreateUploadRequest, opts ...grpc.CallOption) (*CreateUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUploadResponse)
	err := c.cc.Invoke(ctx, MediaService_CreateUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) FinalizeUpload(ctx context.Context, in *FinalizeUploadRequest, opts ...grpc.CallOption) (*FinalizeUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeUploadResponse)
	err := c.cc.Invoke(ctx, MediaService_FinalizeUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) GetDownload(ctx context.Context, in *GetDownloadRequest, opts ...grpc.CallOption) (*GetDownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDownloadResponse)
	err := c.cc.Invoke(ctx, MediaService_GetDownload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaServiceServer is the server API for MediaService service.
// All implementations must embed UnimplementedMediaServiceServer
// for forward compatibility.
//
// MediaService handles media upload and download flows.
type MediaServiceServer interface {
	// HealthCheck verifies service liveness.
	HealthCheck(context.Context, *v1.ServiceHealthRequest) (*v1.ServiceHealthResponse, error)
	// CreateUpload returns a presigned URL for uploading media.
	CreateUpload(context.Context, *CreateUploadRequest) (*CreateUploadResponse, error)
	// FinalizeUpload validates uploaded media and persists metadata.
	FinalizeUpload(context.Context, *FinalizeUploadRequest) (*FinalizeUploadResponse, error)
	// GetDownload returns a presigned URL for downloading media.
	GetDownload(context.Context, *GetDownloadRequest) (*GetDownloadResponse, error)
	mustEmbedUnimplementedMediaServiceServer()
}

// UnimplementedMediaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaServiceServer struct{}

func (UnimplementedMediaServiceServer) HealthCheck(context.Context, *v1.ServiceHealthRequest) (*v1.ServiceHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMediaServiceServer) CreateUpload(context.Context, *CreateUploadRequest) (*CreateUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUpload not implemented")
}
func (UnimplementedMediaServiceServer) FinalizeUpload(context.Context, *FinalizeUploadRequest) (*FinalizeUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinalizeUpload not implemented")
}
func (UnimplementedMediaServiceServer) GetDownload(context.Context, *GetDownloadRequest) (*GetDownloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDownload not implemented")
}
func (UnimplementedMediaServiceServer) mustEmbedUnimplementedMediaServiceServer() {}
func (UnimplementedMediaServiceServer) testEmbeddedByValue()                      {}

// UnsafeMediaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaServiceServer will
// result in compilation errors.
type UnsafeMediaServiceServer interface {
	mustEmbedUnimplementedMediaServiceServer()
}

func RegisterMediaServiceServer(s grpc.ServiceRegistrar, srv MediaServiceServer) {
	// If the following call panics, it indicates UnimplementedMediaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaService_ServiceDesc, srv)
}

func _MediaService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ServiceHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).HealthCheck(ctx, req.(*v1.ServiceHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_CreateUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).CreateUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_CreateUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).CreateUpload(ctx, req.(*CreateUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_FinalizeUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).FinalizeUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_FinalizeUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).FinalizeUpload(ctx, req.(*FinalizeUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_GetDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetDownload(ctx, req.(*GetDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaService_ServiceDesc is the grpc.ServiceDesc for MediaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "media.v1.MediaService",
	HandlerType: (*MediaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _MediaService_HealthCheck_Handler,
		},
		{
			MethodName: "CreateUpload",
			Handler:    _MediaService_CreateUpload_Handler,
		},
		{
			MethodName: "FinalizeUpload",
			Handler:    _MediaService_FinalizeUpload_Handler,
		},
		{
			MethodName: "GetDownload",
			Handler:    _MediaService_GetDownload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "media/v1/service.proto",
}
