// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: media/v1/service.proto

// Media APIs for presigned upload/download workflows.

package mediav1

import (
	v1 "github.com/invenlore/proto/pkg/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_media_v1_service_proto protoreflect.FileDescriptor

const file_media_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x16media/v1/service.proto\x12\bmedia.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x15common/v1/utils.proto\x1a\x17media/v1/messages.proto2\xc6\x03\n" +
	"\fMediaService\x12R\n" +
	"\vHealthCheck\x12\x1f.common.v1.ServiceHealthRequest\x1a .common.v1.ServiceHealthResponse\"\x00\x12p\n" +
	"\fCreateUpload\x12\x1d.media.v1.CreateUploadRequest\x1a\x1e.media.v1.CreateUploadResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/media:createUpload\x12}\n" +
	"\x0eFinalizeUpload\x12\x1f.media.v1.FinalizeUploadRequest\x1a .media.v1.FinalizeUploadResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/media/{media_id}:finalize\x12q\n" +
	"\vGetDownload\x12\x1c.media.v1.GetDownloadRequest\x1a\x1d.media.v1.GetDownloadResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/media/{media_id}:downloadB1Z/github.com/invenlore/proto/pkg/media/v1;mediav1b\x06proto3"

var file_media_v1_service_proto_goTypes = []any{
	(*v1.ServiceHealthRequest)(nil),  // 0: common.v1.ServiceHealthRequest
	(*CreateUploadRequest)(nil),      // 1: media.v1.CreateUploadRequest
	(*FinalizeUploadRequest)(nil),    // 2: media.v1.FinalizeUploadRequest
	(*GetDownloadRequest)(nil),       // 3: media.v1.GetDownloadRequest
	(*v1.ServiceHealthResponse)(nil), // 4: common.v1.ServiceHealthResponse
	(*CreateUploadResponse)(nil),     // 5: media.v1.CreateUploadResponse
	(*FinalizeUploadResponse)(nil),   // 6: media.v1.FinalizeUploadResponse
	(*GetDownloadResponse)(nil),      // 7: media.v1.GetDownloadResponse
}
var file_media_v1_service_proto_depIdxs = []int32{
	0, // 0: media.v1.MediaService.HealthCheck:input_type -> common.v1.ServiceHealthRequest
	1, // 1: media.v1.MediaService.CreateUpload:input_type -> media.v1.CreateUploadRequest
	2, // 2: media.v1.MediaService.FinalizeUpload:input_type -> media.v1.FinalizeUploadRequest
	3, // 3: media.v1.MediaService.GetDownload:input_type -> media.v1.GetDownloadRequest
	4, // 4: media.v1.MediaService.HealthCheck:output_type -> common.v1.ServiceHealthResponse
	5, // 5: media.v1.MediaService.CreateUpload:output_type -> media.v1.CreateUploadResponse
	6, // 6: media.v1.MediaService.FinalizeUpload:output_type -> media.v1.FinalizeUploadResponse
	7, // 7: media.v1.MediaService.GetDownload:output_type -> media.v1.GetDownloadResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_media_v1_service_proto_init() }
func file_media_v1_service_proto_init() {
	if File_media_v1_service_proto != nil {
		return
	}
	file_media_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_v1_service_proto_rawDesc), len(file_media_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_v1_service_proto_goTypes,
		DependencyIndexes: file_media_v1_service_proto_depIdxs,
	}.Build()
	File_media_v1_service_proto = out.File
	file_media_v1_service_proto_goTypes = nil
	file_media_v1_service_proto_depIdxs = nil
}
