// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: identity/v1/internal_service.proto

// Internal identity APIs used by backend services.

package identityv1

import (
	context "context"
	v1 "github.com/invenlore/proto/pkg/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityInternalService_HealthCheck_FullMethodName   = "/identity.v1.IdentityInternalService/HealthCheck"
	IdentityInternalService_GetJWKS_FullMethodName       = "/identity.v1.IdentityInternalService/GetJWKS"
	IdentityInternalService_ValidateToken_FullMethodName = "/identity.v1.IdentityInternalService/ValidateToken"
	IdentityInternalService_Authorize_FullMethodName     = "/identity.v1.IdentityInternalService/Authorize"
	IdentityInternalService_GetUserBrief_FullMethodName  = "/identity.v1.IdentityInternalService/GetUserBrief"
)

// IdentityInternalServiceClient is the client API for IdentityInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IdentityInternalService exposes JWKS and authorization helpers.
type IdentityInternalServiceClient interface {
	// HealthCheck verifies service liveness.
	HealthCheck(ctx context.Context, in *v1.ServiceHealthRequest, opts ...grpc.CallOption) (*v1.ServiceHealthResponse, error)
	// GetJWKS returns the JSON Web Key Set used to validate JWTs.
	GetJWKS(ctx context.Context, in *GetJWKSRequest, opts ...grpc.CallOption) (*GetJWKSResponse, error)
	// ValidateToken validates a JWT and returns subject claims.
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	// Authorize checks access for a specific action/resource.
	Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error)
	// GetUserBrief returns minimal user data without PII.
	GetUserBrief(ctx context.Context, in *GetUserBriefRequest, opts ...grpc.CallOption) (*GetUserBriefResponse, error)
}

type identityInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityInternalServiceClient(cc grpc.ClientConnInterface) IdentityInternalServiceClient {
	return &identityInternalServiceClient{cc}
}

func (c *identityInternalServiceClient) HealthCheck(ctx context.Context, in *v1.ServiceHealthRequest, opts ...grpc.CallOption) (*v1.ServiceHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ServiceHealthResponse)
	err := c.cc.Invoke(ctx, IdentityInternalService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityInternalServiceClient) GetJWKS(ctx context.Context, in *GetJWKSRequest, opts ...grpc.CallOption) (*GetJWKSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJWKSResponse)
	err := c.cc.Invoke(ctx, IdentityInternalService_GetJWKS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityInternalServiceClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, IdentityInternalService_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityInternalServiceClient) Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeResponse)
	err := c.cc.Invoke(ctx, IdentityInternalService_Authorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityInternalServiceClient) GetUserBrief(ctx context.Context, in *GetUserBriefRequest, opts ...grpc.CallOption) (*GetUserBriefResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserBriefResponse)
	err := c.cc.Invoke(ctx, IdentityInternalService_GetUserBrief_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityInternalServiceServer is the server API for IdentityInternalService service.
// All implementations must embed UnimplementedIdentityInternalServiceServer
// for forward compatibility.
//
// IdentityInternalService exposes JWKS and authorization helpers.
type IdentityInternalServiceServer interface {
	// HealthCheck verifies service liveness.
	HealthCheck(context.Context, *v1.ServiceHealthRequest) (*v1.ServiceHealthResponse, error)
	// GetJWKS returns the JSON Web Key Set used to validate JWTs.
	GetJWKS(context.Context, *GetJWKSRequest) (*GetJWKSResponse, error)
	// ValidateToken validates a JWT and returns subject claims.
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	// Authorize checks access for a specific action/resource.
	Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error)
	// GetUserBrief returns minimal user data without PII.
	GetUserBrief(context.Context, *GetUserBriefRequest) (*GetUserBriefResponse, error)
	mustEmbedUnimplementedIdentityInternalServiceServer()
}

// UnimplementedIdentityInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityInternalServiceServer struct{}

func (UnimplementedIdentityInternalServiceServer) HealthCheck(context.Context, *v1.ServiceHealthRequest) (*v1.ServiceHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedIdentityInternalServiceServer) GetJWKS(context.Context, *GetJWKSRequest) (*GetJWKSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJWKS not implemented")
}
func (UnimplementedIdentityInternalServiceServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedIdentityInternalServiceServer) Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authorize not implemented")
}
func (UnimplementedIdentityInternalServiceServer) GetUserBrief(context.Context, *GetUserBriefRequest) (*GetUserBriefResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserBrief not implemented")
}
func (UnimplementedIdentityInternalServiceServer) mustEmbedUnimplementedIdentityInternalServiceServer() {
}
func (UnimplementedIdentityInternalServiceServer) testEmbeddedByValue() {}

// UnsafeIdentityInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityInternalServiceServer will
// result in compilation errors.
type UnsafeIdentityInternalServiceServer interface {
	mustEmbedUnimplementedIdentityInternalServiceServer()
}

func RegisterIdentityInternalServiceServer(s grpc.ServiceRegistrar, srv IdentityInternalServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityInternalService_ServiceDesc, srv)
}

func _IdentityInternalService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ServiceHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityInternalServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityInternalService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityInternalServiceServer).HealthCheck(ctx, req.(*v1.ServiceHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityInternalService_GetJWKS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJWKSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityInternalServiceServer).GetJWKS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityInternalService_GetJWKS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityInternalServiceServer).GetJWKS(ctx, req.(*GetJWKSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityInternalService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityInternalServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityInternalService_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityInternalServiceServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityInternalService_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityInternalServiceServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityInternalService_Authorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityInternalServiceServer).Authorize(ctx, req.(*AuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityInternalService_GetUserBrief_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBriefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityInternalServiceServer).GetUserBrief(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityInternalService_GetUserBrief_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityInternalServiceServer).GetUserBrief(ctx, req.(*GetUserBriefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityInternalService_ServiceDesc is the grpc.ServiceDesc for IdentityInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.v1.IdentityInternalService",
	HandlerType: (*IdentityInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _IdentityInternalService_HealthCheck_Handler,
		},
		{
			MethodName: "GetJWKS",
			Handler:    _IdentityInternalService_GetJWKS_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _IdentityInternalService_ValidateToken_Handler,
		},
		{
			MethodName: "Authorize",
			Handler:    _IdentityInternalService_Authorize_Handler,
		},
		{
			MethodName: "GetUserBrief",
			Handler:    _IdentityInternalService_GetUserBrief_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity/v1/internal_service.proto",
}
