// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: identity/v1/internal_service.proto

// Internal identity APIs used by backend services.

package identityv1

import (
	v1 "github.com/invenlore/proto/pkg/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_identity_v1_internal_service_proto protoreflect.FileDescriptor

const file_identity_v1_internal_service_proto_rawDesc = "" +
	"\n" +
	"\"identity/v1/internal_service.proto\x12\videntity.v1\x1a\x15common/v1/utils.proto\x1a\x1aidentity/v1/messages.proto2\xb4\x03\n" +
	"\x17IdentityInternalService\x12R\n" +
	"\vHealthCheck\x12\x1f.common.v1.ServiceHealthRequest\x1a .common.v1.ServiceHealthResponse\"\x00\x12F\n" +
	"\aGetJWKS\x12\x1b.identity.v1.GetJWKSRequest\x1a\x1c.identity.v1.GetJWKSResponse\"\x00\x12X\n" +
	"\rValidateToken\x12!.identity.v1.ValidateTokenRequest\x1a\".identity.v1.ValidateTokenResponse\"\x00\x12L\n" +
	"\tAuthorize\x12\x1d.identity.v1.AuthorizeRequest\x1a\x1e.identity.v1.AuthorizeResponse\"\x00\x12U\n" +
	"\fGetUserBrief\x12 .identity.v1.GetUserBriefRequest\x1a!.identity.v1.GetUserBriefResponse\"\x00B7Z5github.com/invenlore/proto/pkg/identity/v1;identityv1b\x06proto3"

var file_identity_v1_internal_service_proto_goTypes = []any{
	(*v1.ServiceHealthRequest)(nil),  // 0: common.v1.ServiceHealthRequest
	(*GetJWKSRequest)(nil),           // 1: identity.v1.GetJWKSRequest
	(*ValidateTokenRequest)(nil),     // 2: identity.v1.ValidateTokenRequest
	(*AuthorizeRequest)(nil),         // 3: identity.v1.AuthorizeRequest
	(*GetUserBriefRequest)(nil),      // 4: identity.v1.GetUserBriefRequest
	(*v1.ServiceHealthResponse)(nil), // 5: common.v1.ServiceHealthResponse
	(*GetJWKSResponse)(nil),          // 6: identity.v1.GetJWKSResponse
	(*ValidateTokenResponse)(nil),    // 7: identity.v1.ValidateTokenResponse
	(*AuthorizeResponse)(nil),        // 8: identity.v1.AuthorizeResponse
	(*GetUserBriefResponse)(nil),     // 9: identity.v1.GetUserBriefResponse
}
var file_identity_v1_internal_service_proto_depIdxs = []int32{
	0, // 0: identity.v1.IdentityInternalService.HealthCheck:input_type -> common.v1.ServiceHealthRequest
	1, // 1: identity.v1.IdentityInternalService.GetJWKS:input_type -> identity.v1.GetJWKSRequest
	2, // 2: identity.v1.IdentityInternalService.ValidateToken:input_type -> identity.v1.ValidateTokenRequest
	3, // 3: identity.v1.IdentityInternalService.Authorize:input_type -> identity.v1.AuthorizeRequest
	4, // 4: identity.v1.IdentityInternalService.GetUserBrief:input_type -> identity.v1.GetUserBriefRequest
	5, // 5: identity.v1.IdentityInternalService.HealthCheck:output_type -> common.v1.ServiceHealthResponse
	6, // 6: identity.v1.IdentityInternalService.GetJWKS:output_type -> identity.v1.GetJWKSResponse
	7, // 7: identity.v1.IdentityInternalService.ValidateToken:output_type -> identity.v1.ValidateTokenResponse
	8, // 8: identity.v1.IdentityInternalService.Authorize:output_type -> identity.v1.AuthorizeResponse
	9, // 9: identity.v1.IdentityInternalService.GetUserBrief:output_type -> identity.v1.GetUserBriefResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_identity_v1_internal_service_proto_init() }
func file_identity_v1_internal_service_proto_init() {
	if File_identity_v1_internal_service_proto != nil {
		return
	}
	file_identity_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_internal_service_proto_rawDesc), len(file_identity_v1_internal_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_v1_internal_service_proto_goTypes,
		DependencyIndexes: file_identity_v1_internal_service_proto_depIdxs,
	}.Build()
	File_identity_v1_internal_service_proto = out.File
	file_identity_v1_internal_service_proto_goTypes = nil
	file_identity_v1_internal_service_proto_depIdxs = nil
}
