// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: identity/v1/service.proto

package identityv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_identity_v1_service_proto protoreflect.FileDescriptor

const file_identity_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19identity/v1/service.proto\x12\videntity.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1aidentity/v1/messages.proto2\x82\x05\n" +
	"\x0fIdentityService\x12H\n" +
	"\vHealthCheck\x12\x1a.identity.v1.HealthRequest\x1a\x1b.identity.v1.HealthResponse\"\x00\x12|\n" +
	"\aAddUser\x12\x1b.identity.v1.AddUserRequest\x1a\x1c.identity.v1.AddUserResponse\"6\x92A\x1b\n" +
	"\x05Users\x12\bAdd user\x1a\bAdd user\x82\xd3\xe4\x93\x02\x12:\x01*b\x02id\"\t/v1/users\x12\x86\x01\n" +
	"\aGetUser\x12\x1b.identity.v1.GetUserRequest\x1a\x1c.identity.v1.GetUserResponse\"@\x92A!\n" +
	"\x05Users\x12\bGet user\x1a\x0eGet user by ID\x82\xd3\xe4\x93\x02\x16b\x04user\x12\x0e/v1/users/{id}\x12\x8f\x01\n" +
	"\n" +
	"DeleteUser\x12\x1e.identity.v1.DeleteUserRequest\x1a\x1f.identity.v1.DeleteUserResponse\"@\x92A'\n" +
	"\x05Users\x12\vDelete user\x1a\x11Delete user by ID\x82\xd3\xe4\x93\x02\x10*\x0e/v1/users/{id}\x12\x8b\x01\n" +
	"\tListUsers\x12\x1d.identity.v1.ListUsersRequest\x1a\x1e.identity.v1.ListUsersResponse\"=\x92A#\n" +
	"\x05Users\x12\n" +
	"List users\x1a\x0eList all users\x82\xd3\xe4\x93\x02\x11b\x04user\x12\t/v1/users0\x01B\xb4\x01\x92Az\x12&\n" +
	"\x1cinvenlore.io OpenAPI Swagger2\x06latest*\x01\x02rM\n" +
	"'gRPC-gateway invenlore proto repository\x12\"https://github.com/invenlore/protoZ5github.com/invenlore/proto/pkg/identity/v1;identityv1b\x06proto3"

var file_identity_v1_service_proto_goTypes = []any{
	(*HealthRequest)(nil),      // 0: identity.v1.HealthRequest
	(*AddUserRequest)(nil),     // 1: identity.v1.AddUserRequest
	(*GetUserRequest)(nil),     // 2: identity.v1.GetUserRequest
	(*DeleteUserRequest)(nil),  // 3: identity.v1.DeleteUserRequest
	(*ListUsersRequest)(nil),   // 4: identity.v1.ListUsersRequest
	(*HealthResponse)(nil),     // 5: identity.v1.HealthResponse
	(*AddUserResponse)(nil),    // 6: identity.v1.AddUserResponse
	(*GetUserResponse)(nil),    // 7: identity.v1.GetUserResponse
	(*DeleteUserResponse)(nil), // 8: identity.v1.DeleteUserResponse
	(*ListUsersResponse)(nil),  // 9: identity.v1.ListUsersResponse
}
var file_identity_v1_service_proto_depIdxs = []int32{
	0, // 0: identity.v1.IdentityService.HealthCheck:input_type -> identity.v1.HealthRequest
	1, // 1: identity.v1.IdentityService.AddUser:input_type -> identity.v1.AddUserRequest
	2, // 2: identity.v1.IdentityService.GetUser:input_type -> identity.v1.GetUserRequest
	3, // 3: identity.v1.IdentityService.DeleteUser:input_type -> identity.v1.DeleteUserRequest
	4, // 4: identity.v1.IdentityService.ListUsers:input_type -> identity.v1.ListUsersRequest
	5, // 5: identity.v1.IdentityService.HealthCheck:output_type -> identity.v1.HealthResponse
	6, // 6: identity.v1.IdentityService.AddUser:output_type -> identity.v1.AddUserResponse
	7, // 7: identity.v1.IdentityService.GetUser:output_type -> identity.v1.GetUserResponse
	8, // 8: identity.v1.IdentityService.DeleteUser:output_type -> identity.v1.DeleteUserResponse
	9, // 9: identity.v1.IdentityService.ListUsers:output_type -> identity.v1.ListUsersResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_identity_v1_service_proto_init() }
func file_identity_v1_service_proto_init() {
	if File_identity_v1_service_proto != nil {
		return
	}
	file_identity_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_service_proto_rawDesc), len(file_identity_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_v1_service_proto_goTypes,
		DependencyIndexes: file_identity_v1_service_proto_depIdxs,
	}.Build()
	File_identity_v1_service_proto = out.File
	file_identity_v1_service_proto_goTypes = nil
	file_identity_v1_service_proto_depIdxs = nil
}
