// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: user/service.proto

package user

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_service_proto protoreflect.FileDescriptor

const file_user_service_proto_rawDesc = "" +
	"\n" +
	"\x12user/service.proto\x12\x04user\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x13user/messages.proto2\xc9\x04\n" +
	"\vUserService\x12:\n" +
	"\vHealthCheck\x12\x13.user.HealthRequest\x1a\x14.user.HealthResponse\"\x00\x12t\n" +
	"\aAddUser\x12\x14.user.AddUserRequest\x1a\x15.user.AddUserResponse\"<\x92A\x1b\n" +
	"\x05Users\x12\bAdd user\x1a\bAdd user\x82\xd3\xe4\x93\x02\x18:\x01*b\x04user\"\r/api/v1/users\x12|\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\"D\x92A!\n" +
	"\x05Users\x12\bGet user\x1a\x0eGet user by ID\x82\xd3\xe4\x93\x02\x1ab\x04user\x12\x12/api/v1/users/{id}\x12\x85\x01\n" +
	"\n" +
	"DeleteUser\x12\x17.user.DeleteUserRequest\x1a\x18.user.DeleteUserResponse\"D\x92A'\n" +
	"\x05Users\x12\vDelete user\x1a\x11Delete user by ID\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/users/{id}\x12\x81\x01\n" +
	"\tListUsers\x12\x16.user.ListUsersRequest\x1a\x17.user.ListUsersResponse\"A\x92A#\n" +
	"\x05Users\x12\n" +
	"List users\x1a\x0eList all users\x82\xd3\xe4\x93\x02\x15b\x04user\x12\r/api/v1/users0\x01B\x86\x01\x92AY\x12\x052\x031.0*\x01\x02rM\n" +
	"'gRPC-gateway invenlore proto repository\x12\"https://github.com/invenlore/protoZ(github.com/invenlore/proto/pkg/user;userb\x06proto3"

var file_user_service_proto_goTypes = []any{
	(*HealthRequest)(nil),      // 0: user.HealthRequest
	(*AddUserRequest)(nil),     // 1: user.AddUserRequest
	(*GetUserRequest)(nil),     // 2: user.GetUserRequest
	(*DeleteUserRequest)(nil),  // 3: user.DeleteUserRequest
	(*ListUsersRequest)(nil),   // 4: user.ListUsersRequest
	(*HealthResponse)(nil),     // 5: user.HealthResponse
	(*AddUserResponse)(nil),    // 6: user.AddUserResponse
	(*GetUserResponse)(nil),    // 7: user.GetUserResponse
	(*DeleteUserResponse)(nil), // 8: user.DeleteUserResponse
	(*ListUsersResponse)(nil),  // 9: user.ListUsersResponse
}
var file_user_service_proto_depIdxs = []int32{
	0, // 0: user.UserService.HealthCheck:input_type -> user.HealthRequest
	1, // 1: user.UserService.AddUser:input_type -> user.AddUserRequest
	2, // 2: user.UserService.GetUser:input_type -> user.GetUserRequest
	3, // 3: user.UserService.DeleteUser:input_type -> user.DeleteUserRequest
	4, // 4: user.UserService.ListUsers:input_type -> user.ListUsersRequest
	5, // 5: user.UserService.HealthCheck:output_type -> user.HealthResponse
	6, // 6: user.UserService.AddUser:output_type -> user.AddUserResponse
	7, // 7: user.UserService.GetUser:output_type -> user.GetUserResponse
	8, // 8: user.UserService.DeleteUser:output_type -> user.DeleteUserResponse
	9, // 9: user.UserService.ListUsers:output_type -> user.ListUsersResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_service_proto_init() }
func file_user_service_proto_init() {
	if File_user_service_proto != nil {
		return
	}
	file_user_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_proto_rawDesc), len(file_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_proto_goTypes,
		DependencyIndexes: file_user_service_proto_depIdxs,
	}.Build()
	File_user_service_proto = out.File
	file_user_service_proto_goTypes = nil
	file_user_service_proto_depIdxs = nil
}
